# Predict sql injection attacks

### Initail package imports

In [1]:
import pandas as pd
import tensorflow.keras
import os
import re
import nltk
#nltk.download('stopwords')
from nltk.corpus import stopwords

### Data Cleaning Functions

In [2]:
def cleanSqliData(data):
    for i in range(len(data)):
        data[i] = data[i].replace('\n', '')
        data[i] = data[i].replace('%20', ' ')
        data[i] = data[i].replace('=', ' = ')
        data[i] = data[i].replace('((', ' (( ')
        data[i] = data[i].replace('))', ' )) ')
        data[i] = data[i].replace('(', ' ( ')
        data[i] = data[i].replace(')', ' ) ')
        data[i] = data[i].lower()
    return data

In [3]:
stopWords = set(stopwords.words('english')) 
def removeStopWords(posts):
    filtered = ''
    for x in posts.split(' '):
        if x not in stopWords:
            filtered += ' ' + x
    return filtered

### Data Loading and Preprocessing

> SQLI Data from external sources

        Source: https://github.com/foospidy/payloads/tree/master/other/sqli
        File name: sqlifuzzer.txt
        Status : Ok
        Concerns:  
            1. Eliminated \n from each line ending
            2. UrlDecoding to handle space and other characters

In [4]:
path = './data/sqlifuzzer.txt'

In [5]:
sqlFuzzingLines = []
file = open(path, "r")
for x in file:
    sqlFuzzingLines.append(x)

In [6]:
sqlFuzzingLines = cleanSqliData(sqlFuzzingLines)

        Source: https://github.com/foospidy/payloads/tree/master/other/sqli
        File Name: camoufl4g3.txt
        Status : ok

In [7]:
path = './data/camoufl4g3.txt'

In [8]:
sqlCamoufl4g3Lines = []
file = open(path, "r")
for x in file:
    sqlCamoufl4g3Lines.append(x)

In [9]:
sqlCamoufl4g3Lines = cleanSqliData(sqlCamoufl4g3Lines)

        Source: https://github.com/foospidy/payloads/tree/master/other/sqli
        File Name: libinjection-bypasses.txt
        Status: Ok
        Concerns: Strip &()o1: from start

In [10]:
path = './data/libinjection-bypasses.txt'

In [11]:
sqlBypassLines=[]
file = open(path, "r")
for x in file:
    sqlBypassLines.append(x)

In [12]:
sqlBypassLines = cleanSqliData(sqlBypassLines)

In [13]:
# if don't want &(*)* sign in beginning of each sentence then run next code else don't

for i in range(len(sqlBypassLines)):
    sentence = sqlBypassLines[i]
    try:
        sqlBypassLines[i] = sentence.split(':')[1]
    except:
        pass

        Source: https://github.com/foospidy/payloads/tree/master/other/sqli
        File Name: sqli_OWASP.txt
        Status: ok

In [14]:
path = './data/sqli_OSWAP.txt'

In [15]:
sqlOwaspLines = []
file = open(path, "r")
for x in file:
    sqlOwaspLines.append(x)

In [16]:
sqlOwaspLines = cleanSqliData(sqlOwaspLines)

        Source: https://github.com/danielmiessler/SecLists/tree/master/Fuzzing/SQLi
        File Name: Generic-SQLi.txt
        Status: Ok
        Concerns: UrlDecoding to handle space and other characters

In [17]:
path = './data/Generic-SQLi.txt'

In [18]:
genericSqliLines = []
file = open(path, "r")
for x in file:
    genericSqliLines.append(x)

In [19]:
genericSqliLines = cleanSqliData(genericSqliLines)

        Source: https://github.com/mrsuman2002/SQL-Injection-Authentication-Bypass-Cheat-Sheet
        File Name: SQL_Injection_Cheat_Sheet.txt
        Status: Ok

In [20]:
path = './data/SQL_Injection_Cheat_Sheet.txt'

In [21]:
sqlInjectionCheatSheetLines = []
file = open(path, "r")
for x in file:
    sqlInjectionCheatSheetLines.append(x)

In [22]:
sqlInjectionCheatSheetLines = cleanSqliData(sqlInjectionCheatSheetLines)

> Plain Data from external sources

        Source: https://github.com/tungpv98/Detect-Sql-Injection-by-Machine-Learning/tree/ebeb3287931677a3a42f11a7a08dbc13e374ff05/Sql-Injection/source/trainingdata
        File name: plain.txt
        Concerns: 
            1. Keep seperator as Aw3s0meSc0t7
            2. Remove last few records which containing URLs

In [23]:
path = './data/'
file = "plain.txt"

In [24]:
df = pd.read_csv(os.path.join(path,file), sep='Aw3s0meSc0t7', names=['benign'], header=None, engine='python')

In [25]:
plain_text = df['benign'].values  # get sentences

In [26]:
# convert from list to string
plain_data = ''
for x in plain_text:
    plain_data += " " + x

In [27]:
plain_data = removeStopWords(plain_data)  # remove stop words
plain_data = plain_data.split('.')        # split sentences

In [28]:
# seperate words inside tags
for i in range(len(plain_data)):
    plain_data[i] = plain_data[i].replace('<', ' <')
    plain_data[i] = plain_data[i].replace('>', '> ')
    plain_data[i] = plain_data[i].replace('=', ' = ')

In [29]:
print("Benign records: ", len(plain_data))

Benign records:  5369

> Plain Data (Self Created)

In [30]:
# read self created benign data

path = './data/benign_data.txt'
benign_data = []
file = open(path, "r")
for x in file:
    benign_data.append(x)

In [31]:
len(benign_data)

620

In [32]:
benign_sentence = []
for i in benign_data:
    sentences = i.split('.')
    
    for sentence in sentences:
        benign_sentence.append(sentence)

In [33]:
len(benign_sentence)

1167

> SQLi Data (Self Created)

In [34]:
# read self created sqli data

path = './data/sqli_for_training.txt'
sqli_data = []
file = open(path, "r")
for x in file:
    sqli_data.append(x)

In [35]:
len(sqli_data)

330

### Statistics

In [36]:
print(f'''
    SQLi:
    \tFuzzing :\t\t\t{len(sqlFuzzingLines)}
    \tCamoufl4gs :\t\t\t{len(sqlCamoufl4g3Lines)}
    \tBypass :\t\t\t{len(sqlBypassLines)}
    \tOwasp :\t\t\t\t{len(sqlOwaspLines)}
    \tGeneric :\t\t\t{len(genericSqliLines)}
    \tSql Injection Cheat Sheet:\t{len(sqlInjectionCheatSheetLines)}
    \tSQLi(Self) :\t\t\t{len(sqli_data)}
    =========================================================
    \t\tTotal SQLi data :\t{ len(genericSqliLines) + len(sqlOwaspLines) + len(sqlBypassLines) + len(sqlCamoufl4g3Lines) + len(sqlFuzzingLines) + len(sqlInjectionCheatSheetLines) + len(sqli_data)} 
    Plain/Benign:
    \tPlain(External) :\t\t{len(plain_data)}
    \tBenign(Self) :\t\t\t{len(benign_sentence)}
    =========================================================
    \t\tTotal Plain Data :\t{ len(benign_sentence) + len(plain_data) }
    ---------------------------------------------------------
    \t\t\tTotal Records :\t{ len(genericSqliLines) + len(sqlOwaspLines) + len(sqlBypassLines) + len(sqlCamoufl4g3Lines) + len(sqlFuzzingLines) + len(sqlInjectionCheatSheetLines) + len(sqli_data) + len(benign_sentence) + len(plain_data)}
    ''')

    SQLi:
    	Fuzzing :			86
    	Camoufl4gs :			77
    	Bypass :			474
    	Owasp :				6692
    	Generic :			308
    	Sql Injection Cheat Sheet:	47
    	SQLi(Self) :			330
    =========================================================
    		Total SQLi data :	8014
    Plain/Benign:
    	Plain(External) :		5369
    	Benign(Self) :			1167
    =========================================================
    		Total Plain Data :	6536
    ---------------------------------------------------------
    			Total Records :	14550

### Collating all SQLi attack data

In [37]:
all_sqli_sentence = sqlOwaspLines + sqlBypassLines + sqlCamoufl4g3Lines + sqlFuzzingLines + genericSqliLines + sqlInjectionCheatSheetLines + sqli_data

In [38]:
len(all_sqli_sentence)

8014

### Collating all Plain/Benign data

In [39]:
all_plain_sentence = benign_sentence + plain_data

In [40]:
len(all_plain_sentence)

6536

### Final Cleaning of data before Generating Combined Data

>>> Converting numerics in sqli data to standard string

In [41]:
# replace numeric values by a standard string 'numeric'
def optional_numeric_to_numeric(all_sqli_sentence):
    for i in range(len(all_sqli_sentence)):
        all_sqli_sentence[i]=re.sub(r"\d+", "numeric",all_sqli_sentence[i])    
    return all_sqli_sentence

In [42]:
all_sqli_sentence = optional_numeric_to_numeric(all_sqli_sentence)

In [43]:
all_sqli_sentence[:25]

['\' or "',
 '-- or # ',
 "' or 'numeric",
 "' or numeric -- -",
 '" or ""  =  "',
 '" or numeric  =  numeric -- -',
 "' or ''  =  '",
 "' = '",
 "'like'",
 "' = numeric--+",
 ' or numeric = numeric',
 "' or 'x' = 'x",
 "' and id is null; --",
 "'''''''''''''union select 'numeric",
 'and numeric',
 'and numeric',
 'and true',
 'and false',
 'numeric-false',
 'numeric-true',
 'numeric*numeric',
 '-numeric',
 "numeric' order by numeric--+",
 "numeric' order by numeric--+",
 "numeric' order by numeric--+"]

>>> Removing Empty or single character strings from benign data

In [44]:
def optional_single_char_string_removal(all_plain_sentence):
    for i in range(len(all_plain_sentence)-1,-1,-1):
        if all_plain_sentence[i] == ' ' or all_plain_sentence[i] == '' or all_plain_sentence[i] == '\n' or all_plain_sentence[i] == '\t' or all_plain_sentence[i] == '\r':
            all_plain_sentence.remove(all_plain_sentence[i])
    return all_plain_sentence

In [45]:
all_plain_sentence = optional_single_char_string_removal(all_plain_sentence)

In [46]:
all_plain_sentence[:5]

['Remember to give benign data',
 ' eat bread or butter',
 ' can you wait for me',
 'wait for me',
 ' waitfor me']

## Post Data Cleaning Statistics

In [47]:
print(f'''
#####################################
####        Post Cleaning :      ####
#####################################
Total SQLi Data:\t{len(all_sqli_sentence)}
Total Plain Data:\t{len(all_plain_sentence)}
=====================================
Combined Total Data:\t{len(all_sqli_sentence)+len(all_plain_sentence)}''')

#####################################
####        Post Cleaning :      ####
#####################################
Total SQLi Data:	8014
Total Plain Data:	6275
=====================================
Combined Total Data:	14289

### Generating single merged data file including both type of data, Benign and SQLi (with lables)

In [48]:
combined_data = []

In [49]:
# Setting SQLi data lable as 1

for i in all_sqli_sentence:
    combined_data.append((i,1))

In [50]:
# Setting Benign data lable as 0

for i in all_plain_sentence:
    combined_data.append((i,0))

In [51]:
# convert to dataframe
df=pd.DataFrame(combined_data,columns=['Sentence','Label'])

In [52]:
df.head()

            Sentence  Label
0             ' or "      1
1           -- or #       1
2      ' or 'numeric      1
3  ' or numeric -- -      1
4      " or ""  =  "      1

### Save data as csv

In [53]:
df.to_csv('sqli.csv', index=False, encoding='utf-16')

### Reading Data from CSV

In [54]:
df=pd.read_csv('sqli.csv',encoding='utf-16')
df.drop_duplicates(inplace= True, ignore_index=True)

In [55]:
df.head()

            Sentence  Label
0             ' or "      1
1           -- or #       1
2      ' or 'numeric      1
3  ' or numeric -- -      1
4      " or ""  =  "      1

In [56]:
len(df[df['Label']==0])

5879

In [57]:
len(df[df['Label']==1])

5360

In [58]:
#Vectorization NEW METHOD
def lNewStringVectorizer(inp=''): # can take df or string
    import pandas as pd
    import re
    
    def Newvectorizer(df):
        def num_of_SQLI_keywords(df):###############################SQL keyword count##########################
            SQL=["ALL","ADD CONSTRAINT","ALTER","DROP","ALTER COLUMN","ALTER TABLE","AND","ANY","AS","ASC","BACKUP DATABASE","BETWEEN","CASE","CHECK","COLUMN","CONSTRAINT","OPENROWSET","CREATE","INDEX","OR REPLACE VIEW","TABLE","PROCEDURE","UNIQUE INDEX","VIEW","DATABASE","DEFAULT","DELETE","DESC","DECLARE","DISTINCT","DROP COLUMN","DROP CONSTRAINT","DROP DATABASE","DROP DEFAULT","DROP INDEX","DROP TABLE","DROP VIEW","EXEC","EXISTS","FOREIGN KEY","FROM","FULL OUTER JOIN","GROUP BY","HAVING","IN","INDEX","INNER JOIN","INSERT INTO","INSERT INTO SELECT","SELECT USER","IS NULL","IS NOT NULL","LEFT JOIN","LIKE","LIMIT","NOT","NOT NULL","OR","ORDER BY","OUTER JOIN","PRIMARY KEY","PROCEDURE","RIGHT JOIN","ROWNUM","SELECT","DISTINCT","OUTFILE","INTO OUTFILE","SET","TOP","TRUNCATE TABLE","UNION","UNIQUE","UPDATE","VALUES","VIEW","WHERE","LOAD DATA","INFILE","CONCAT", "LOAD_FILE"]
            def countkey(k,r):
                symbols=['~','`','!','@','#','$','%','^','&','*','(',')','-','_','+','=','{','}','[',']','|','\\','/',':',';','"',"'",'<','>',',','?','.']
                rr=r['Sentence']
                for j in symbols:
                    rr=rr.replace('  ',' ')
                    rr=rr.replace(j,' '+j+' ')
                    rr=rr.replace('  ',' ')
                rr=" "+rr+" "
                rr=rr.lower()
                return rr.count(' '+k.lower()+' ') + rr.count(' '+k+' ')
            for a in SQL:
                df[a]=df.apply (lambda row: countkey(a,row), axis=1)
            return df

        def num_of_unsual_comb(df):###############################unusual combo count##########################
            combi_regexes={
                    "Number'":r"\d+'",
                    "Number":r"numeric",
                    "+Number,":r"\+\d+,",
                    "@@":r"@@[a-zA-Z]",
                    "Number--":r"\d+--",
                    "Alphabets--":r"[a-zA-Z]+--",
                    '%NumberAlphabet':r"%\d+[a-zA-Z]*",
                    '0x2f Encoded':r"0x\d+([a-zA-Z]|)",
                    'Multiline Comments':r"(\\/*)|(\*\/)",
                    'Multiline Comments with MYSQL syntax': r"\/\*! *\d+",
                    'Always true and other such conditions': r"(\"|')(( *\))|) ((or)|(OR)) ((\d+(=|>|<|!=|<>)\d+)|([a-zA-Z]+=[a-zA-Z]+))(( )|)(((--)|(\/\*)|(#))|)",
            }
            
            def countcombo(k,r):
                return len(re.findall(k, r['Sentence']))

            for a in combi_regexes:
                df[a]=df.apply (lambda row: countcombo(combi_regexes[a],row), axis=1)

            return df

        def num_of_symbols(df):
              symbols=['~','`','!','@','#','$','%','^','&','*','(',')','-','_','+','=','{','}','[',']','|','\\','/',':',';','"',"'",'<','>',',','❡','?']

              def countsymbols(symbol,row):
                  string = row['Sentence']
                  string = " " + string + " "
                  string = string.lower()
                  return  string.count(symbol)

              for symbol in symbols:
                  df[symbol] = df.apply (lambda row: countsymbols(symbol, row), axis=1)
              return df

        #calculate length
        df['rlen'] = df['Sentence'].str.split(" ").str.join("").str.len()
        df.dropna(inplace=True) 
        #count keywords
        df = num_of_SQLI_keywords(df)
        #count Unusual combos
        df = num_of_unsual_comb(df)
        #number of Symbols
        df = num_of_symbols(df)

        return df

    if(isinstance(inp, str)): #
        qdf = pd.DataFrame({'Sentence':[inp]})
        qdf=Newvectorizer(qdf)
        qdf=qdf[qdf.columns[1:]]
        return qdf
    else:
        return Newvectorizer(inp)

In [59]:
df=lNewStringVectorizer(inp=df)
df.head()

,Sentence,Label,rlen,ALL,ADD CONSTRAINT,ALTER,DROP,ALTER COLUMN,ALTER TABLE,AND,...,/,:,;,"""",',<,>,",",❡,?
0,"' or """,1,4,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
1,-- or #,1,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,' or 'numeric,1,11,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
3,' or numeric -- -,1,13,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,""" or """" = """,1,7,0,0,0,0,0,0,0,...,0,0,0,4,0,0,0,0,0,0

### New Vectorizer

In [94]:
#Vectorization NEW METHOD
def NewStringVectorizer(inp=''): # can take df or string
    import pandas as pd
    import re
    
    def Newvectorizer(df):
        def num_of_SQLI_keywords(df):###############################SQL keyword count##########################
            SQL=["ALL","ADD CONSTRAINT","ALTER","DROP","ALTER COLUMN","ALTER TABLE","AND","ANY","AS","ASC","BACKUP DATABASE","BETWEEN","CASE","CHECK","COLUMN","CONSTRAINT","OPENROWSET","CREATE","INDEX","OR REPLACE VIEW","TABLE","PROCEDURE","UNIQUE INDEX","VIEW","DATABASE","DEFAULT","DELETE","DESC","DECLARE","DISTINCT","DROP COLUMN","DROP CONSTRAINT","DROP DATABASE","DROP DEFAULT","DROP INDEX","DROP TABLE","DROP VIEW","EXEC","EXISTS","FOREIGN KEY","FROM","FULL OUTER JOIN","GROUP BY","HAVING","IN","INDEX","INNER JOIN","INSERT INTO","INSERT INTO SELECT","SELECT USER","IS NULL","IS NOT NULL","LEFT JOIN","LIKE","LIMIT","NOT","NOT NULL","OR","ORDER BY","OUTER JOIN","PRIMARY KEY","PROCEDURE","RIGHT JOIN","ROWNUM","SELECT","DISTINCT","OUTFILE","INTO OUTFILE","SET","TOP","TRUNCATE TABLE","UNION","UNIQUE","UPDATE","VALUES","VIEW","WHERE","LOAD DATA","INFILE","CONCAT", "LOAD_FILE"]
            def countkey(k,r):
                symbols=['~','`','!','@','#','$','%','^','&','*','(',')','-','_','+','=','{','}','[',']','|','\\','/',':',';','"',"'",'<','>',',','?','.']
                rr=r['Sentence']
                for j in symbols:
                    rr=rr.replace('  ',' ')
                    rr=rr.replace(j,' '+j+' ')
                    rr=rr.replace('  ',' ')
                rr=" "+rr+" "
                rr=rr.lower()
                return rr.count(' '+k.lower()+' ') + rr.count(' '+k+' ')
            for a in SQL:
                df[a]=df.apply (lambda row: countkey(a,row), axis=1)
            return df

        def num_of_unsual_comb(df):###############################unusual combo count##########################
            combi_regexes={
                    "Number'":r"\d+'",
                    "Number":r"numeric",
                    "+Number,":r"\+\d+,",
                    "@@":r"@@[a-zA-Z]",
                    "Number--":r"\d+--",
                    "Alphabets--":r"[a-zA-Z]+--",
                    '%NumberAlphabet':r"%\d+[a-zA-Z]*",
                    '0x2f Encoded':r"0x\d+([a-zA-Z]|)",
                    'Multiline Comments':r"(\\/*)|(\*\/)",
                    'Multiline Comments with MYSQL syntax': r"\/\*! *\d+",
                    'Always true and other such conditions': r"(\"|')(( *\))|) ((or)|(OR)) ((\d+(=|>|<|!=|<>)\d+)|([a-zA-Z]+=[a-zA-Z]+))(( )|)(((--)|(\/\*)|(#))|)",
            }
            
            def countcombo(k,r):
                return len(re.findall(k, r['Sentence']))

            for a in combi_regexes:
                df[a]=df.apply (lambda row: countcombo(combi_regexes[a],row), axis=1)

            return df

        def num_of_symbols(df):
              symbols=['~','`','!','@','#','$','%','^','&','*','(',')','-','_','+','=','{','}','[',']','|','\\','/',':',';','"',"'",'<','>',',','❡','?']

              def countsymbols(symbol,row):
                  string = row['Sentence']
                  string = " " + string + " "
                  string = string.lower()
                  return  string.count(symbol)

              for symbol in symbols:
                  df[symbol] = df.apply (lambda row: countsymbols(symbol, row), axis=1)
              return df

        #calculate length
        df['rlen'] = df['Sentence'].str.split(" ").str.join("").str.len()
        df.dropna(inplace=True) 
        #count keywords
        df = num_of_SQLI_keywords(df)
        #count Unusual combos
        df = num_of_unsual_comb(df)
        #number of Symbols
        df = num_of_symbols(df)

        return df

    if(isinstance(inp, str)): #
        qdf = pd.DataFrame({'Sentence':[inp]})
        qdf=Newvectorizer(qdf)
        qdf=qdf[qdf.columns[1:]]
        return qdf
    else:
        return Newvectorizer(inp)

nv=NewStringVectorizer

### Suffling data and spilting

In [95]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,Sentence,Label,rlen,ALL,ADD CONSTRAINT,ALTER,DROP,ALTER COLUMN,ALTER TABLE,AND,...,/,:,;,"""",',<,>,",",❡,?
0,numeric' and ( numeric = numeric ) *numeric--...,1,42,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1,numeric and ( select ( case when ( numeric ...,1,113,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2,what is title of email\n,0,19,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,and numeric = numeric and 'pklz' = 'pkly,1,33,0,0,0,0,0,0,2,...,0,0,0,0,3,0,0,0,0,0
4,-numeric ) ) or numeric = numeric\unumeric,1,36,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [96]:
#Drop Nan Values
df = df.dropna(subset=['Sentence'])
df = df.sample(frac=1).reset_index(drop=True)

In [63]:
x = df[df.columns[2:]]

In [64]:
x.shape

(11239, 121)

In [65]:
y = df['Label']

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
# split train test data

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [68]:
print(f'''x_train.shape :\t{x_train.shape}
y_train.shape :\t{ y_train.shape }
x_test.shape :\t{ x_test.shape }
y_test.shape :\t{ y_test.shape }
''')

x_train.shape :	(8991, 121)
y_train.shape :	(8991,)
x_test.shape :	(2248, 121)
y_test.shape :	(2248,)

### Model Prepration Imports

In [69]:
%pip install --upgrade wandb

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wandb in /Users/avinashkarhana/Library/Python/3.8/lib/python/site-packages (0.12.1)
Requirement already satisfied: docker-pycreds>=0.4.0 in /Library/Python/3.8/site-packages (from wandb) (0.4.0)
Requirement already satisfied: configparser>=3.8.1 in /Library/Python/3.8/site-packages (from wandb) (5.0.0)
Requirement already satisfied: protobuf>=3.12.0 in /Library/Python/3.8/site-packages (from wandb) (3.12.2)
Requirement already satisfied: six>=1.13.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from wandb) (1.15.0)
Requirement already satisfied: requests<3,>=2.0.0 in /Library/Python/3.8/site-packages (from wandb) (2.24.0)
Requirement already satisfied: GitPython>=1.0.0 in /Library/Python/3.8/site-packages (from wandb) (3.1.8)
Requirement already satisfied: PyYAML in /Library/Python/3.8/site-packages (from wandb) (5.3.1)
Requirement already satisfied: promise<3,>=2.0 in /Library/Python/3.8/site-packages (from wandb) (2.3)
Requirement already satisfied: psutil>=5.0.0 in /Library/Python/3.8/site-packages (from wandb) (5.7.2)
Requirement already satisfied: shortuuid>=0.5.0 in /Library/Python/3.8/site-packages (from wandb) (1.0.1)
Requirement already satisfied: subprocess32>=3.5.3 in /Library/Python/3.8/site-packages (from wandb) (3.5.4)
Requirement already satisfied: pathtools in /Library/Python/3.8/site-packages (from wandb) (0.1.2)
Requirement already satisfied: sentry-sdk>=1.0.0 in /Users/avinashkarhana/Library/Python/3.8/lib/python/site-packages (from wandb) (1.3.1)
Requirement already satisfied: Click!=8.0.0,>=7.0 in /Library/Python/3.8/site-packages (from wandb) (7.1.2)
Requirement already satisfied: python-dateutil>=2.6.1 in /Library/Python/3.8/site-packages (from wandb) (2.8.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Library/Python/3.8/site-packages (from GitPython>=1.0.0->wandb) (4.0.5)
Requirement already satisfied: smmap<4,>=3.0.1 in /Library/Python/3.8/site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb) (3.0.4)
Requirement already satisfied: setuptools in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from protobuf>=3.12.0->wandb) (41.2.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Python/3.8/site-packages (from requests<3,>=2.0.0->wandb) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /Users/avinashkarhana/Library/Python/3.8/lib/python/site-packages (from requests<3,>=2.0.0->wandb) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /Library/Python/3.8/site-packages (from requests<3,>=2.0.0->wandb) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /Library/Python/3.8/site-packages (from requests<3,>=2.0.0->wandb) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

In [70]:
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorboard.plugins.hparams import api as hp
from sklearn.metrics import precision_score, recall_score, accuracy_score
import wandb
from wandb.keras import WandbCallback

### Confusion Matrix

In [71]:
def calculateAccuracy(truePositive,trueNegative,falsePositive,falseNegative):
    return ( truePositive + trueNegative ) / ( truePositive + trueNegative + falsePositive + falseNegative )

def calculatePrecision(truePositive,falsePositive):
    return truePositive / ( truePositive + falsePositive )

def calculateRecall(truePositive,falseNegative):
    return truePositive / (truePositive+falseNegative)

def generateConfusionMatrix(test,prediction):
    truePositive = 0
    trueNegative = 0
    falsePositive = 0
    falseNegative = 0

    for true, pred in zip(test,prediction):
        if true == 1:
            if pred == true:
                truePositive += 1
            else:
                falseNegative += 1
        elif true == 0:
            if pred == true:
                trueNegative += 1
            else:
                falsePositive += 1
    print(f'''True Positive:\t{truePositive}
    True Negative:\n{trueNegative}
    False Positive:\n{falsePositive}
    False Negative:\n{falseNegative}
    ''')
    accuracy = calculateAccuracy(truePositive, trueNegative, falsePositive, falseNegative)
    precision = calculatePrecision(truePositive, falsePositive)
    recall = calculateRecall(truePositive, falseNegative)
    
    return (accuracy, precision, recall)

### Model Prepration and training

In [72]:
losses=['binary_crossentropy','categorical_crossentropy','kl_divergence']
optimizers=['adam','sgd','rmsprop','adagrad','adadelta','adamax']
models={}
for a in losses:
   for b in optimizers:
       print("\n---------------------------------------------------------------\n\n############################ Model: "+a+"@"+b+" ############################\n")
       tensorflow.keras.backend.clear_session()
       #Weight And Biases Login
       #run=wandb.init(project="iwaf",name="NN Model# "+a+"@"+b) # uncomment this line to run on wandb
       input_dim = x_train.shape[1]  # Number of features
       model = Sequential()
       model.add(tensorflow.keras.layers.BatchNormalization(input_dim=input_dim))
       model.add(tensorflow.keras.layers.Dense(1024, activation='relu'))
       model.add(tensorflow.keras.layers.Dense(1024, activation='relu'))
       #model.add(tensorflow.keras.layers.Dense(512, activation='relu'))
       #model.add(tensorflow.keras.layers.Dense(128, activation='relu'))
       # model.add(keras.layers.Dense(20,  activation='relu'))
       # model.add(keras.layers.Dense(10,  activation='tanh'))
       # model.add(layers.Flatten())
       # model.add(keras.layers.Dense(1024, activation='relu'))
       #model.add(tensorflow.keras.layers.BatchNormalization())
       model.add(tensorflow.keras.layers.Dropout(0.5))
       model.add(tensorflow.keras.layers.Dense(1, activation='sigmoid'))
       model.compile(loss = a, optimizer = b, metrics = ['accuracy'])
       model.summary()
       print()
       model.fit(x_train,y_train,
                           epochs=20,
                           verbose=True,
                           validation_data=(x_test, y_test),
                           batch_size=1024,
                           #callbacks=[WandbCallback()], # uncomment this line to use wandb
                           )
       models[a+"@"+b]=model
       del model
       tensorflow.keras.backend.clear_session()
       #run.finish() # uncomment this line to use wandb

---------------------------------------------------------------

############################ Model: binary_crossentropy@adam ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 242ms/step - loss: 0.2868 - accuracy: 0.8733 - val_loss: 0.3442 - val_accuracy: 0.8283
Epoch 2/20
9/9 [==============================] - 2s 211ms/step - loss: 0.1024 - accuracy: 0.9714 - val_loss: 0.2643 - val_accuracy: 0.9395
Epoch 3/20
9/9 [==============================] - 2s 224ms/step - loss: 0.0723 - accuracy: 0.9778 - val_loss: 0.2496 - val_accuracy: 0.9515
Epoch 4/20
9/9 [==============================] - 2s 172ms/step - loss: 0.0584 - accuracy: 0.9810 - val_loss: 0.1950 - val_accuracy: 0.9755
Epoch 5/20
9/9 [==============================] - 2s 172ms/step - loss: 0.0485 - accuracy: 0.9843 - val_loss: 0.1368 - val_accuracy: 0.9813
Epoch 6/20
9/9 [==============================] - 1s 156ms/step - loss: 0.0422 - accuracy: 0.9869 - val_loss: 0.1116 - val_accuracy: 0.9827
Epoch 7/20
9/9 [==============================] - 1s 159ms/step - loss: 0.0370 - accuracy: 0.9897 - val_loss: 0.1241 - val_accuracy: 0.9827
Epoch 8/20
9/9 [==============================] - 1s 150ms/step - loss: 0.0363 - accuracy: 0.9899 - val_loss: 0.0948 - val_accuracy: 0.9835
Epoch 9/20
9/9 [==============================] - 2s 250ms/step - loss: 0.0350 - accuracy: 0.9895 - val_loss: 0.0722 - val_accuracy: 0.9853
Epoch 10/20
9/9 [==============================] - 1s 162ms/step - loss: 0.0321 - accuracy: 0.9905 - val_loss: 0.0698 - val_accuracy: 0.9853
Epoch 11/20
9/9 [==============================] - 2s 178ms/step - loss: 0.0318 - accuracy: 0.9909 - val_loss: 0.0584 - val_accuracy: 0.9867
Epoch 12/20
9/9 [==============================] - ETA: 0s - loss: 0.0300 - accuracy: 0.99 - 2s 229ms/step - loss: 0.0300 - accuracy: 0.9911 - val_loss: 0.0473 - val_accuracy: 0.9875
Epoch 13/20
9/9 [==============================] - 2s 170ms/step - loss: 0.0310 - accuracy: 0.9911 - val_loss: 0.0471 - val_accuracy: 0.9867
Epoch 14/20
9/9 [==============================] - 2s 199ms/step - loss: 0.0301 - accuracy: 0.9912 - val_loss: 0.0437 - val_accuracy: 0.9884
Epoch 15/20
9/9 [==============================] - 2s 210ms/step - loss: 0.0279 - accuracy: 0.9924 - val_loss: 0.0433 - val_accuracy: 0.9884
Epoch 16/20
9/9 [==============================] - 2s 274ms/step - loss: 0.0279 - accuracy: 0.9912 - val_loss: 0.0413 - val_accuracy: 0.9893
Epoch 17/20
9/9 [==============================] - 2s 230ms/step - loss: 0.0358 - accuracy: 0.9912 - val_loss: 0.0380 - val_accuracy: 0.9902
Epoch 18/20
9/9 [==============================] - 2s 206ms/step - loss: 0.0266 - accuracy: 0.9919 - val_loss: 0.0385 - val_accuracy: 0.9907
Epoch 19/20
9/9 [==============================] - 1s 158ms/step - loss: 0.0282 - accuracy: 0.9922 - val_loss: 0.0399 - val_accuracy: 0.9893
Epoch 20/20
9/9 [==============================] - 2s 172ms/step - loss: 0.0279 - accuracy: 0.9922 - val_loss: 0.0411 - val_accuracy: 0.9893

---------------------------------------------------------------

############################ Model: binary_crossentropy@sgd ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 207ms/step - loss: 0.6527 - accuracy: 0.6252 - val_loss: 0.6074 - val_accuracy: 0.5943
Epoch 2/20
9/9 [==============================] - 1s 157ms/step - loss: 0.5954 - accuracy: 0.8145 - val_loss: 0.5818 - val_accuracy: 0.6833
Epoch 3/20
9/9 [==============================] - 2s 181ms/step - loss: 0.5493 - accuracy: 0.8823 - val_loss: 0.5593 - val_accuracy: 0.7438
Epoch 4/20
9/9 [==============================] - 2s 199ms/step - loss: 0.5114 - accuracy: 0.9022 - val_loss: 0.5386 - val_accuracy: 0.8488
Epoch 5/20
9/9 [==============================] - 2s 178ms/step - loss: 0.4796 - accuracy: 0.9223 - val_loss: 0.5186 - val_accuracy: 0.9133
Epoch 6/20
9/9 [==============================] - 2s 179ms/step - loss: 0.4489 - accuracy: 0.9352 - val_loss: 0.4986 - val_accuracy: 0.9408
Epoch 7/20
9/9 [==============================] - 2s 189ms/step - loss: 0.4215 - accuracy: 0.9398 - val_loss: 0.4786 - val_accuracy: 0.9640
Epoch 8/20
9/9 [==============================] - 2s 186ms/step - loss: 0.3977 - accuracy: 0.9448 - val_loss: 0.4588 - val_accuracy: 0.9698
Epoch 9/20
9/9 [==============================] - 2s 272ms/step - loss: 0.3746 - accuracy: 0.9493 - val_loss: 0.4391 - val_accuracy: 0.9715
Epoch 10/20
9/9 [==============================] - 2s 170ms/step - loss: 0.3521 - accuracy: 0.9521 - val_loss: 0.4200 - val_accuracy: 0.9720
Epoch 11/20
9/9 [==============================] - 1s 152ms/step - loss: 0.3368 - accuracy: 0.9513 - val_loss: 0.4016 - val_accuracy: 0.9702
Epoch 12/20
9/9 [==============================] - 1s 146ms/step - loss: 0.3202 - accuracy: 0.9531 - val_loss: 0.3836 - val_accuracy: 0.9689
Epoch 13/20
9/9 [==============================] - 1s 147ms/step - loss: 0.3008 - accuracy: 0.9551 - val_loss: 0.3660 - val_accuracy: 0.9693
Epoch 14/20
9/9 [==============================] - 2s 175ms/step - loss: 0.2853 - accuracy: 0.9561 - val_loss: 0.3493 - val_accuracy: 0.9680
Epoch 15/20
9/9 [==============================] - 2s 182ms/step - loss: 0.2713 - accuracy: 0.9577 - val_loss: 0.3333 - val_accuracy: 0.9675
Epoch 16/20
9/9 [==============================] - 2s 275ms/step - loss: 0.2638 - accuracy: 0.9566 - val_loss: 0.3182 - val_accuracy: 0.9671
Epoch 17/20
9/9 [==============================] - 2s 184ms/step - loss: 0.2496 - accuracy: 0.9567 - val_loss: 0.3039 - val_accuracy: 0.9666
Epoch 18/20
9/9 [==============================] - 2s 197ms/step - loss: 0.2390 - accuracy: 0.9591 - val_loss: 0.2905 - val_accuracy: 0.9657
Epoch 19/20
9/9 [==============================] - 2s 200ms/step - loss: 0.2298 - accuracy: 0.9591 - val_loss: 0.2779 - val_accuracy: 0.9657
Epoch 20/20
9/9 [==============================] - 2s 182ms/step - loss: 0.2221 - accuracy: 0.9584 - val_loss: 0.2660 - val_accuracy: 0.9653

---------------------------------------------------------------

############################ Model: binary_crossentropy@rmsprop ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20

9/9 [==============================] - 2s 238ms/step - loss: 0.2707 - accuracy: 0.8814 - val_loss: 0.3109 - val_accuracy: 0.8968
Epoch 2/20
9/9 [==============================] - 2s 187ms/step - loss: 0.0878 - accuracy: 0.9748 - val_loss: 0.2839 - val_accuracy: 0.9284
Epoch 3/20
9/9 [==============================] - 1s 165ms/step - loss: 0.0720 - accuracy: 0.9782 - val_loss: 0.1815 - val_accuracy: 0.9773
Epoch 4/20
9/9 [==============================] - 1s 163ms/step - loss: 0.0623 - accuracy: 0.9806 - val_loss: 0.2358 - val_accuracy: 0.9453
Epoch 5/20
9/9 [==============================] - 1s 147ms/step - loss: 0.0635 - accuracy: 0.9814 - val_loss: 0.1382 - val_accuracy: 0.9831
Epoch 6/20
9/9 [==============================] - 2s 194ms/step - loss: 0.0458 - accuracy: 0.9871 - val_loss: 0.0980 - val_accuracy: 0.9831
Epoch 7/20
9/9 [==============================] - 2s 170ms/step - loss: 0.0534 - accuracy: 0.9867 - val_loss: 0.0831 - val_accuracy: 0.9818
Epoch 8/20
9/9 [==============================] - 1s 148ms/step - loss: 0.0455 - accuracy: 0.9873 - val_loss: 0.0763 - val_accuracy: 0.9853
Epoch 9/20
9/9 [==============================] - 1s 157ms/step - loss: 0.0432 - accuracy: 0.9871 - val_loss: 0.0586 - val_accuracy: 0.9867
Epoch 10/20
9/9 [==============================] - 2s 168ms/step - loss: 0.0397 - accuracy: 0.9891 - val_loss: 0.0650 - val_accuracy: 0.9840
Epoch 11/20
9/9 [==============================] - 1s 159ms/step - loss: 0.0391 - accuracy: 0.9895 - val_loss: 0.0452 - val_accuracy: 0.9893
Epoch 12/20
9/9 [==============================] - 2s 174ms/step - loss: 0.0416 - accuracy: 0.9881 - val_loss: 0.0443 - val_accuracy: 0.9884
Epoch 13/20
9/9 [==============================] - 1s 147ms/step - loss: 0.0334 - accuracy: 0.9907 - val_loss: 0.0481 - val_accuracy: 0.9867
Epoch 14/20
9/9 [==============================] - 2s 169ms/step - loss: 0.0335 - accuracy: 0.9910 - val_loss: 0.0568 - val_accuracy: 0.9867
Epoch 15/20
9/9 [==============================] - 1s 148ms/step - loss: 0.0392 - accuracy: 0.9897 - val_loss: 0.0445 - val_accuracy: 0.9893
Epoch 16/20
9/9 [==============================] - 2s 178ms/step - loss: 0.0310 - accuracy: 0.9909 - val_loss: 0.0469 - val_accuracy: 0.9880
Epoch 17/20
9/9 [==============================] - 2s 169ms/step - loss: 0.0447 - accuracy: 0.9889 - val_loss: 0.0418 - val_accuracy: 0.9898
Epoch 18/20
9/9 [==============================] - 1s 154ms/step - loss: 0.0295 - accuracy: 0.9910 - val_loss: 0.0438 - val_accuracy: 0.9898
Epoch 19/20
9/9 [==============================] - 2s 183ms/step - loss: 0.0374 - accuracy: 0.9900 - val_loss: 0.0413 - val_accuracy: 0.9898
Epoch 20/20
9/9 [==============================] - 2s 171ms/step - loss: 0.0316 - accuracy: 0.9913 - val_loss: 0.0422 - val_accuracy: 0.9902

---------------------------------------------------------------

############################ Model: binary_crossentropy@adagrad ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 201ms/step - loss: 0.6478 - accuracy: 0.7031 - val_loss: 0.6244 - val_accuracy: 0.5836
Epoch 2/20
9/9 [==============================] - 1s 150ms/step - loss: 0.6239 - accuracy: 0.7801 - val_loss: 0.6143 - val_accuracy: 0.6730
Epoch 3/20
9/9 [==============================] - 2s 218ms/step - loss: 0.6083 - accuracy: 0.8240 - val_loss: 0.6049 - val_accuracy: 0.7135
Epoch 4/20
9/9 [==============================] - 2s 188ms/step - loss: 0.5911 - accuracy: 0.8497 - val_loss: 0.5961 - val_accuracy: 0.7633
Epoch 5/20
9/9 [==============================] - 1s 166ms/step - loss: 0.5755 - accuracy: 0.8616 - val_loss: 0.5873 - val_accuracy: 0.8252
Epoch 6/20
9/9 [==============================] - 2s 198ms/step - loss: 0.5618 - accuracy: 0.8822 - val_loss: 0.5787 - val_accuracy: 0.8599
Epoch 7/20
9/9 [==============================] - 2s 197ms/step - loss: 0.5493 - accuracy: 0.8914 - val_loss: 0.5702 - val_accuracy: 0.8972
Epoch 8/20
9/9 [==============================] - 2s 177ms/step - loss: 0.5361 - accuracy: 0.9013 - val_loss: 0.5616 - val_accuracy: 0.9181
Epoch 9/20
9/9 [==============================] - 2s 169ms/step - loss: 0.5256 - accuracy: 0.9045 - val_loss: 0.5531 - val_accuracy: 0.9337
Epoch 10/20
9/9 [==============================] - 1s 166ms/step - loss: 0.5161 - accuracy: 0.9107 - val_loss: 0.5445 - val_accuracy: 0.9484
Epoch 11/20
9/9 [==============================] - 2s 192ms/step - loss: 0.5044 - accuracy: 0.9181 - val_loss: 0.5360 - val_accuracy: 0.9591
Epoch 12/20
9/9 [==============================] - 2s 236ms/step - loss: 0.4931 - accuracy: 0.9230 - val_loss: 0.5273 - val_accuracy: 0.9631
Epoch 13/20
9/9 [==============================] - 2s 249ms/step - loss: 0.4848 - accuracy: 0.9255 - val_loss: 0.5187 - val_accuracy: 0.9653
Epoch 14/20
9/9 [==============================] - 2s 173ms/step - loss: 0.4753 - accuracy: 0.9315 - val_loss: 0.5101 - val_accuracy: 0.9684
Epoch 15/20
9/9 [==============================] - 2s 167ms/step - loss: 0.4657 - accuracy: 0.9348 - val_loss: 0.5016 - val_accuracy: 0.9684
Epoch 16/20
9/9 [==============================] - 2s 244ms/step - loss: 0.4553 - accuracy: 0.9358 - val_loss: 0.4930 - val_accuracy: 0.9706
Epoch 17/20
9/9 [==============================] - 2s 222ms/step - loss: 0.4476 - accuracy: 0.9391 - val_loss: 0.4845 - val_accuracy: 0.9706
Epoch 18/20
9/9 [==============================] - 1s 161ms/step - loss: 0.4399 - accuracy: 0.9364 - val_loss: 0.4760 - val_accuracy: 0.9706
Epoch 19/20
9/9 [==============================] - 2s 189ms/step - loss: 0.4325 - accuracy: 0.9426 - val_loss: 0.4677 - val_accuracy: 0.9711
Epoch 20/20
9/9 [==============================] - 2s 187ms/step - loss: 0.4252 - accuracy: 0.9445 - val_loss: 0.4593 - val_accuracy: 0.9684

---------------------------------------------------------------

############################ Model: binary_crossentropy@adadelta ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 266ms/step - loss: 0.7214 - accuracy: 0.5721 - val_loss: 0.7356 - val_accuracy: 0.5205
Epoch 2/20

9/9 [==============================] - 1s 147ms/step - loss: 0.7157 - accuracy: 0.5801 - val_loss: 0.7194 - val_accuracy: 0.5409
Epoch 3/20
9/9 [==============================] - 2s 175ms/step - loss: 0.7086 - accuracy: 0.6006 - val_loss: 0.7105 - val_accuracy: 0.5698
Epoch 4/20
9/9 [==============================] - 2s 172ms/step - loss: 0.7053 - accuracy: 0.6099 - val_loss: 0.7039 - val_accuracy: 0.6045
Epoch 5/20
9/9 [==============================] - 2s 214ms/step - loss: 0.6994 - accuracy: 0.6233 - val_loss: 0.6985 - val_accuracy: 0.6335
Epoch 6/20
9/9 [==============================] - 2s 194ms/step - loss: 0.6984 - accuracy: 0.6365 - val_loss: 0.6936 - val_accuracy: 0.6619
Epoch 7/20
9/9 [==============================] - 2s 171ms/step - loss: 0.6915 - accuracy: 0.6481 - val_loss: 0.6892 - val_accuracy: 0.6931
Epoch 8/20
9/9 [==============================] - 2s 188ms/step - loss: 0.6865 - accuracy: 0.6658 - val_loss: 0.6850 - val_accuracy: 0.7144
Epoch 9/20
9/9 [==============================] - 2s 216ms/step - loss: 0.6805 - accuracy: 0.6780 - val_loss: 0.6810 - val_accuracy: 0.7353
Epoch 10/20
9/9 [==============================] - 1s 166ms/step - loss: 0.6798 - accuracy: 0.6836 - val_loss: 0.6771 - val_accuracy: 0.7549
Epoch 11/20
9/9 [==============================] - 1s 148ms/step - loss: 0.6716 - accuracy: 0.7003 - val_loss: 0.6733 - val_accuracy: 0.7709
Epoch 12/20
9/9 [==============================] - 2s 197ms/step - loss: 0.6702 - accuracy: 0.7114 - val_loss: 0.6696 - val_accuracy: 0.7905
Epoch 13/20
9/9 [==============================] - 2s 199ms/step - loss: 0.6632 - accuracy: 0.7264 - val_loss: 0.6660 - val_accuracy: 0.8167
Epoch 14/20
9/9 [==============================] - 2s 216ms/step - loss: 0.6608 - accuracy: 0.7406 - val_loss: 0.6624 - val_accuracy: 0.8332
Epoch 15/20
9/9 [==============================] - 2s 177ms/step - loss: 0.6549 - accuracy: 0.7539 - val_loss: 0.6588 - val_accuracy: 0.8465
Epoch 16/20
9/9 [==============================] - 1s 160ms/step - loss: 0.6510 - accuracy: 0.7617 - val_loss: 0.6553 - val_accuracy: 0.8692
Epoch 17/20
9/9 [==============================] - 2s 193ms/step - loss: 0.6470 - accuracy: 0.7709 - val_loss: 0.6518 - val_accuracy: 0.8852
Epoch 18/20
9/9 [==============================] - 2s 192ms/step - loss: 0.6445 - accuracy: 0.7724 - val_loss: 0.6483 - val_accuracy: 0.8950
Epoch 19/20
9/9 [==============================] - 2s 186ms/step - loss: 0.6405 - accuracy: 0.7860 - val_loss: 0.6448 - val_accuracy: 0.9012
Epoch 20/20
9/9 [==============================] - 2s 235ms/step - loss: 0.6368 - accuracy: 0.8034 - val_loss: 0.6413 - val_accuracy: 0.9093

---------------------------------------------------------------

############################ Model: binary_crossentropy@adamax ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 238ms/step - loss: 0.2868 - accuracy: 0.9126 - val_loss: 0.3319 - val_accuracy: 0.8706
Epoch 2/20
9/9 [==============================] - 2s 209ms/step - loss: 0.1067 - accuracy: 0.9672 - val_loss: 0.2609 - val_accuracy: 0.9337
Epoch 3/20
9/9 [==============================] - 2s 170ms/step - loss: 0.0843 - accuracy: 0.9759 - val_loss: 0.2130 - val_accuracy: 0.9582
Epoch 4/20
9/9 [==============================] - 1s 163ms/step - loss: 0.0738 - accuracy: 0.9788 - val_loss: 0.2096 - val_accuracy: 0.9622
Epoch 5/20
9/9 [==============================] - 2s 172ms/step - loss: 0.0670 - accuracy: 0.9806 - val_loss: 0.1703 - val_accuracy: 0.9751
Epoch 6/20
9/9 [==============================] - 2s 191ms/step - loss: 0.0586 - accuracy: 0.9824 - val_loss: 0.1651 - val_accuracy: 0.9746
Epoch 7/20
9/9 [==============================] - 2s 179ms/step - loss: 0.0545 - accuracy: 0.9821 - val_loss: 0.1290 - val_accuracy: 0.9786
Epoch 8/20
9/9 [==============================] - 1s 155ms/step - loss: 0.0516 - accuracy: 0.9847 - val_loss: 0.1119 - val_accuracy: 0.9818
Epoch 9/20
9/9 [==============================] - 2s 173ms/step - loss: 0.0471 - accuracy: 0.9863 - val_loss: 0.1046 - val_accuracy: 0.9818
Epoch 10/20
9/9 [==============================] - 1s 154ms/step - loss: 0.0451 - accuracy: 0.9868 - val_loss: 0.0907 - val_accuracy: 0.9831
Epoch 11/20
9/9 [==============================] - 1s 162ms/step - loss: 0.0426 - accuracy: 0.9880 - val_loss: 0.0802 - val_accuracy: 0.9835
Epoch 12/20
9/9 [==============================] - 2s 186ms/step - loss: 0.0413 - accuracy: 0.9882 - val_loss: 0.0738 - val_accuracy: 0.9844
Epoch 13/20
9/9 [==============================] - 1s 155ms/step - loss: 0.0398 - accuracy: 0.9879 - val_loss: 0.0657 - val_accuracy: 0.9849
Epoch 14/20
9/9 [==============================] - 2s 170ms/step - loss: 0.0384 - accuracy: 0.9892 - val_loss: 0.0620 - val_accuracy: 0.9849
Epoch 15/20
9/9 [==============================] - 2s 183ms/step - loss: 0.0384 - accuracy: 0.9893 - val_loss: 0.0540 - val_accuracy: 0.9853
Epoch 16/20
9/9 [==============================] - 1s 166ms/step - loss: 0.0358 - accuracy: 0.9897 - val_loss: 0.0541 - val_accuracy: 0.9858
Epoch 17/20
9/9 [==============================] - 2s 204ms/step - loss: 0.0345 - accuracy: 0.9898 - val_loss: 0.0501 - val_accuracy: 0.9867
Epoch 18/20
9/9 [==============================] - 2s 178ms/step - loss: 0.0343 - accuracy: 0.9901 - val_loss: 0.0474 - val_accuracy: 0.9871
Epoch 19/20
9/9 [==============================] - 2s 179ms/step - loss: 0.0333 - accuracy: 0.9902 - val_loss: 0.0462 - val_accuracy: 0.9871
Epoch 20/20
9/9 [==============================] - 2s 168ms/step - loss: 0.0328 - accuracy: 0.9908 - val_loss: 0.0447 - val_accuracy: 0.9880

---------------------------------------------------------------

############################ Model: categorical_crossentropy@adam ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 179ms/step - loss: 5.6495e-08 - accuracy: 0.5768 - val_loss: 5.8279e-08 - val_accuracy: 0.7838
Epoch 2/20
9/9 [==============================] - 1s 158ms/step - loss: 5.6495e-08 - accuracy: 0.5933 - val_loss: 5.8279e-08 - val_accuracy: 0.7673
Epoch 3/20

9/9 [==============================] - 2s 176ms/step - loss: 5.6495e-08 - accuracy: 0.5856 - val_loss: 5.8279e-08 - val_accuracy: 0.7611
Epoch 4/20
9/9 [==============================] - 1s 144ms/step - loss: 5.6495e-08 - accuracy: 0.5849 - val_loss: 5.8279e-08 - val_accuracy: 0.7375
Epoch 5/20
9/9 [==============================] - 1s 139ms/step - loss: 5.6495e-08 - accuracy: 0.5794 - val_loss: 5.8279e-08 - val_accuracy: 0.6993
Epoch 6/20
9/9 [==============================] - 2s 169ms/step - loss: 5.6495e-08 - accuracy: 0.5815 - val_loss: 5.8279e-08 - val_accuracy: 0.6432
Epoch 7/20
9/9 [==============================] - 1s 153ms/step - loss: 5.6495e-08 - accuracy: 0.5771 - val_loss: 5.8279e-08 - val_accuracy: 0.6174
Epoch 8/20
9/9 [==============================] - 1s 144ms/step - loss: 5.6495e-08 - accuracy: 0.5860 - val_loss: 5.8279e-08 - val_accuracy: 0.6005
Epoch 9/20
9/9 [==============================] - 1s 147ms/step - loss: 5.6495e-08 - accuracy: 0.5849 - val_loss: 5.8279e-08 - val_accuracy: 0.5907
Epoch 10/20
9/9 [==============================] - 1s 131ms/step - loss: 5.6495e-08 - accuracy: 0.5874 - val_loss: 5.8279e-08 - val_accuracy: 0.5787
Epoch 11/20
9/9 [==============================] - 1s 157ms/step - loss: 5.6495e-08 - accuracy: 0.5818 - val_loss: 5.8279e-08 - val_accuracy: 0.5663
Epoch 12/20
9/9 [==============================] - 2s 189ms/step - loss: 5.6495e-08 - accuracy: 0.5824 - val_loss: 5.8279e-08 - val_accuracy: 0.5601
Epoch 13/20
9/9 [==============================] - 1s 166ms/step - loss: 5.6495e-08 - accuracy: 0.5845 - val_loss: 5.8279e-08 - val_accuracy: 0.5538
Epoch 14/20
9/9 [==============================] - 2s 179ms/step - loss: 5.6495e-08 - accuracy: 0.5844 - val_loss: 5.8279e-08 - val_accuracy: 0.5503
Epoch 15/20
9/9 [==============================] - 2s 178ms/step - loss: 5.6495e-08 - accuracy: 0.5866 - val_loss: 5.8279e-08 - val_accuracy: 0.5427
Epoch 16/20
9/9 [==============================] - 1s 166ms/step - loss: 5.6495e-08 - accuracy: 0.5839 - val_loss: 5.8279e-08 - val_accuracy: 0.5329
Epoch 17/20
9/9 [==============================] - 1s 159ms/step - loss: 5.6495e-08 - accuracy: 0.5822 - val_loss: 5.8279e-08 - val_accuracy: 0.5316
Epoch 18/20
9/9 [==============================] - 1s 153ms/step - loss: 5.6495e-08 - accuracy: 0.5834 - val_loss: 5.8279e-08 - val_accuracy: 0.5258
Epoch 19/20
9/9 [==============================] - 2s 169ms/step - loss: 5.6495e-08 - accuracy: 0.5891 - val_loss: 5.8279e-08 - val_accuracy: 0.5205
Epoch 20/20
9/9 [==============================] - 2s 178ms/step - loss: 5.6495e-08 - accuracy: 0.5777 - val_loss: 5.8279e-08 - val_accuracy: 0.5205

---------------------------------------------------------------

############################ Model: categorical_crossentropy@sgd ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 189ms/step - loss: 5.6495e-08 - accuracy: 0.4182 - val_loss: 5.8279e-08 - val_accuracy: 0.4155
Epoch 2/20
9/9 [==============================] - 1s 152ms/step - loss: 5.6495e-08 - accuracy: 0.4160 - val_loss: 5.8279e-08 - val_accuracy: 0.4079
Epoch 3/20
9/9 [==============================] - 1s 143ms/step - loss: 5.6495e-08 - accuracy: 0.4130 - val_loss: 5.8279e-08 - val_accuracy: 0.3977
Epoch 4/20
9/9 [==============================] - 1s 148ms/step - loss: 5.6495e-08 - accuracy: 0.4244 - val_loss: 5.8279e-08 - val_accuracy: 0.3941
Epoch 5/20
9/9 [==============================] - 1s 152ms/step - loss: 5.6495e-08 - accuracy: 0.4199 - val_loss: 5.8279e-08 - val_accuracy: 0.3892
Epoch 6/20
9/9 [==============================] - 1s 130ms/step - loss: 5.6495e-08 - accuracy: 0.4261 - val_loss: 5.8279e-08 - val_accuracy: 0.3866
Epoch 7/20
9/9 [==============================] - 1s 140ms/step - loss: 5.6495e-08 - accuracy: 0.4203 - val_loss: 5.8279e-08 - val_accuracy: 0.3790
Epoch 8/20
9/9 [==============================] - 1s 132ms/step - loss: 5.6495e-08 - accuracy: 0.4157 - val_loss: 5.8279e-08 - val_accuracy: 0.3763
Epoch 9/20
9/9 [==============================] - 1s 143ms/step - loss: 5.6495e-08 - accuracy: 0.4270 - val_loss: 5.8279e-08 - val_accuracy: 0.3746
Epoch 10/20
9/9 [==============================] - 1s 135ms/step - loss: 5.6495e-08 - accuracy: 0.4206 - val_loss: 5.8279e-08 - val_accuracy: 0.3728
Epoch 11/20
9/9 [==============================] - 1s 148ms/step - loss: 5.6495e-08 - accuracy: 0.4175 - val_loss: 5.8279e-08 - val_accuracy: 0.3728
Epoch 12/20
9/9 [==============================] - 1s 140ms/step - loss: 5.6495e-08 - accuracy: 0.4251 - val_loss: 5.8279e-08 - val_accuracy: 0.3732
Epoch 13/20
9/9 [==============================] - 1s 142ms/step - loss: 5.6495e-08 - accuracy: 0.4183 - val_loss: 5.8279e-08 - val_accuracy: 0.3710
Epoch 14/20
9/9 [==============================] - 1s 145ms/step - loss: 5.6495e-08 - accuracy: 0.4236 - val_loss: 5.8279e-08 - val_accuracy: 0.3625
Epoch 15/20
9/9 [==============================] - 2s 205ms/step - loss: 5.6495e-08 - accuracy: 0.4077 - val_loss: 5.8279e-08 - val_accuracy: 0.3599
Epoch 16/20
9/9 [==============================] - 2s 172ms/step - loss: 5.6495e-08 - accuracy: 0.4251 - val_loss: 5.8279e-08 - val_accuracy: 0.3590
Epoch 17/20
9/9 [==============================] - 2s 170ms/step - loss: 5.6495e-08 - accuracy: 0.4255 - val_loss: 5.8279e-08 - val_accuracy: 0.3603
Epoch 18/20
9/9 [==============================] - 1s 166ms/step - loss: 5.6495e-08 - accuracy: 0.4271 - val_loss: 5.8279e-08 - val_accuracy: 0.3599
Epoch 19/20
9/9 [==============================] - 2s 185ms/step - loss: 5.6495e-08 - accuracy: 0.4089 - val_loss: 5.8279e-08 - val_accuracy: 0.3603
Epoch 20/20
9/9 [==============================] - 2s 170ms/step - loss: 5.6495e-08 - accuracy: 0.4174 - val_loss: 5.8279e-08 - val_accuracy: 0.3634

---------------------------------------------------------------

############################ Model: categorical_crossentropy@rmsprop ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 199ms/step - loss: 5.6495e-08 - accuracy: 0.5847 - val_loss: 5.8279e-08 - val_accuracy: 0.5120
Epoch 2/20

9/9 [==============================] - 1s 159ms/step - loss: 5.6495e-08 - accuracy: 0.5679 - val_loss: 5.8279e-08 - val_accuracy: 0.5351
Epoch 3/20
9/9 [==============================] - 2s 201ms/step - loss: 5.6495e-08 - accuracy: 0.5781 - val_loss: 5.8279e-08 - val_accuracy: 0.5329
Epoch 4/20
9/9 [==============================] - 1s 141ms/step - loss: 5.6495e-08 - accuracy: 0.5781 - val_loss: 5.8279e-08 - val_accuracy: 0.5338
Epoch 5/20
9/9 [==============================] - 1s 160ms/step - loss: 5.6495e-08 - accuracy: 0.5762 - val_loss: 5.8279e-08 - val_accuracy: 0.5343
Epoch 6/20
9/9 [==============================] - 1s 143ms/step - loss: 5.6495e-08 - accuracy: 0.5631 - val_loss: 5.8279e-08 - val_accuracy: 0.5356
Epoch 7/20
9/9 [==============================] - 1s 153ms/step - loss: 5.6495e-08 - accuracy: 0.5741 - val_loss: 5.8279e-08 - val_accuracy: 0.5351
Epoch 8/20
9/9 [==============================] - 1s 146ms/step - loss: 5.6495e-08 - accuracy: 0.5706 - val_loss: 5.8279e-08 - val_accuracy: 0.5356
Epoch 9/20
9/9 [==============================] - 2s 173ms/step - loss: 5.6495e-08 - accuracy: 0.5768 - val_loss: 5.8279e-08 - val_accuracy: 0.5369
Epoch 10/20
9/9 [==============================] - 1s 155ms/step - loss: 5.6495e-08 - accuracy: 0.5713 - val_loss: 5.8279e-08 - val_accuracy: 0.5378
Epoch 11/20
9/9 [==============================] - 1s 161ms/step - loss: 5.6495e-08 - accuracy: 0.5730 - val_loss: 5.8279e-08 - val_accuracy: 0.5391
Epoch 12/20
9/9 [==============================] - 1s 160ms/step - loss: 5.6495e-08 - accuracy: 0.5728 - val_loss: 5.8279e-08 - val_accuracy: 0.5400
Epoch 13/20
9/9 [==============================] - 1s 163ms/step - loss: 5.6495e-08 - accuracy: 0.5724 - val_loss: 5.8279e-08 - val_accuracy: 0.5405
Epoch 14/20
9/9 [==============================] - 1s 154ms/step - loss: 5.6495e-08 - accuracy: 0.5750 - val_loss: 5.8279e-08 - val_accuracy: 0.5409
Epoch 15/20
9/9 [==============================] - 1s 157ms/step - loss: 5.6495e-08 - accuracy: 0.5759 - val_loss: 5.8279e-08 - val_accuracy: 0.5405
Epoch 16/20
9/9 [==============================] - 1s 153ms/step - loss: 5.6495e-08 - accuracy: 0.5687 - val_loss: 5.8279e-08 - val_accuracy: 0.5396
Epoch 17/20
9/9 [==============================] - 1s 154ms/step - loss: 5.6495e-08 - accuracy: 0.5648 - val_loss: 5.8279e-08 - val_accuracy: 0.5405
Epoch 18/20
9/9 [==============================] - 1s 151ms/step - loss: 5.6495e-08 - accuracy: 0.5758 - val_loss: 5.8279e-08 - val_accuracy: 0.5414
Epoch 19/20
9/9 [==============================] - 1s 151ms/step - loss: 5.6495e-08 - accuracy: 0.5712 - val_loss: 5.8279e-08 - val_accuracy: 0.5423
Epoch 20/20
9/9 [==============================] - 1s 147ms/step - loss: 5.6495e-08 - accuracy: 0.5781 - val_loss: 5.8279e-08 - val_accuracy: 0.5436

---------------------------------------------------------------

############################ Model: categorical_crossentropy@adagrad ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 1s 166ms/step - loss: 5.6495e-08 - accuracy: 0.5292 - val_loss: 5.8279e-08 - val_accuracy: 0.7193
Epoch 2/20
9/9 [==============================] - 1s 142ms/step - loss: 5.6495e-08 - accuracy: 0.5247 - val_loss: 5.8279e-08 - val_accuracy: 0.6637
Epoch 3/20
9/9 [==============================] - 1s 152ms/step - loss: 5.6495e-08 - accuracy: 0.5322 - val_loss: 5.8279e-08 - val_accuracy: 0.6121
Epoch 4/20
9/9 [==============================] - 1s 145ms/step - loss: 5.6495e-08 - accuracy: 0.5334 - val_loss: 5.8279e-08 - val_accuracy: 0.5965
Epoch 5/20
9/9 [==============================] - 1s 156ms/step - loss: 5.6495e-08 - accuracy: 0.5316 - val_loss: 5.8279e-08 - val_accuracy: 0.5930
Epoch 6/20
9/9 [==============================] - 1s 159ms/step - loss: 5.6495e-08 - accuracy: 0.5340 - val_loss: 5.8279e-08 - val_accuracy: 0.5778
Epoch 7/20
9/9 [==============================] - 2s 184ms/step - loss: 5.6495e-08 - accuracy: 0.5373 - val_loss: 5.8279e-08 - val_accuracy: 0.5609
Epoch 8/20
9/9 [==============================] - 1s 140ms/step - loss: 5.6495e-08 - accuracy: 0.5359 - val_loss: 5.8279e-08 - val_accuracy: 0.5489
Epoch 9/20
9/9 [==============================] - 1s 148ms/step - loss: 5.6495e-08 - accuracy: 0.5301 - val_loss: 5.8279e-08 - val_accuracy: 0.5409
Epoch 10/20
9/9 [==============================] - 1s 134ms/step - loss: 5.6495e-08 - accuracy: 0.5335 - val_loss: 5.8279e-08 - val_accuracy: 0.5280
Epoch 11/20
9/9 [==============================] - 1s 149ms/step - loss: 5.6495e-08 - accuracy: 0.5362 - val_loss: 5.8279e-08 - val_accuracy: 0.5240
Epoch 12/20
9/9 [==============================] - 1s 129ms/step - loss: 5.6495e-08 - accuracy: 0.5324 - val_loss: 5.8279e-08 - val_accuracy: 0.5169
Epoch 13/20
9/9 [==============================] - 1s 145ms/step - loss: 5.6495e-08 - accuracy: 0.5380 - val_loss: 5.8279e-08 - val_accuracy: 0.5138
Epoch 14/20
9/9 [==============================] - 2s 171ms/step - loss: 5.6495e-08 - accuracy: 0.5284 - val_loss: 5.8279e-08 - val_accuracy: 0.5129
Epoch 15/20
9/9 [==============================] - 1s 151ms/step - loss: 5.6495e-08 - accuracy: 0.5362 - val_loss: 5.8279e-08 - val_accuracy: 0.5089
Epoch 16/20
9/9 [==============================] - 1s 143ms/step - loss: 5.6495e-08 - accuracy: 0.5244 - val_loss: 5.8279e-08 - val_accuracy: 0.5080
Epoch 17/20
9/9 [==============================] - 1s 152ms/step - loss: 5.6495e-08 - accuracy: 0.5373 - val_loss: 5.8279e-08 - val_accuracy: 0.5040
Epoch 18/20
9/9 [==============================] - 1s 149ms/step - loss: 5.6495e-08 - accuracy: 0.5388 - val_loss: 5.8279e-08 - val_accuracy: 0.5013
Epoch 19/20
9/9 [==============================] - 1s 151ms/step - loss: 5.6495e-08 - accuracy: 0.5341 - val_loss: 5.8279e-08 - val_accuracy: 0.4987
Epoch 20/20
9/9 [==============================] - 1s 155ms/step - loss: 5.6495e-08 - accuracy: 0.5288 - val_loss: 5.8279e-08 - val_accuracy: 0.4987

---------------------------------------------------------------

############################ Model: categorical_crossentropy@adadelta ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20

9/9 [==============================] - 1s 167ms/step - loss: 5.6495e-08 - accuracy: 0.3669 - val_loss: 5.8279e-08 - val_accuracy: 0.3003
Epoch 2/20
9/9 [==============================] - 1s 152ms/step - loss: 5.6495e-08 - accuracy: 0.3734 - val_loss: 5.8279e-08 - val_accuracy: 0.2931
Epoch 3/20
9/9 [==============================] - 2s 174ms/step - loss: 5.6495e-08 - accuracy: 0.3706 - val_loss: 5.8279e-08 - val_accuracy: 0.3003
Epoch 4/20
9/9 [==============================] - 1s 156ms/step - loss: 5.6495e-08 - accuracy: 0.3664 - val_loss: 5.8279e-08 - val_accuracy: 0.3043
Epoch 5/20
9/9 [==============================] - 1s 154ms/step - loss: 5.6495e-08 - accuracy: 0.3659 - val_loss: 5.8279e-08 - val_accuracy: 0.3136
Epoch 6/20
9/9 [==============================] - 1s 146ms/step - loss: 5.6495e-08 - accuracy: 0.3733 - val_loss: 5.8279e-08 - val_accuracy: 0.3283
Epoch 7/20
9/9 [==============================] - 1s 152ms/step - loss: 5.6495e-08 - accuracy: 0.3748 - val_loss: 5.8279e-08 - val_accuracy: 0.3350
Epoch 8/20
9/9 [==============================] - 1s 139ms/step - loss: 5.6495e-08 - accuracy: 0.3683 - val_loss: 5.8279e-08 - val_accuracy: 0.3341
Epoch 9/20
9/9 [==============================] - 1s 151ms/step - loss: 5.6495e-08 - accuracy: 0.3706 - val_loss: 5.8279e-08 - val_accuracy: 0.3381
Epoch 10/20
9/9 [==============================] - 1s 155ms/step - loss: 5.6495e-08 - accuracy: 0.3716 - val_loss: 5.8279e-08 - val_accuracy: 0.3416
Epoch 11/20
9/9 [==============================] - 1s 153ms/step - loss: 5.6495e-08 - accuracy: 0.3738 - val_loss: 5.8279e-08 - val_accuracy: 0.3465
Epoch 12/20
9/9 [==============================] - 1s 144ms/step - loss: 5.6495e-08 - accuracy: 0.3717 - val_loss: 5.8279e-08 - val_accuracy: 0.3514
Epoch 13/20
9/9 [==============================] - 1s 151ms/step - loss: 5.6495e-08 - accuracy: 0.3719 - val_loss: 5.8279e-08 - val_accuracy: 0.3572
Epoch 14/20
9/9 [==============================] - 1s 140ms/step - loss: 5.6495e-08 - accuracy: 0.3776 - val_loss: 5.8279e-08 - val_accuracy: 0.3594
Epoch 15/20
9/9 [==============================] - 1s 147ms/step - loss: 5.6495e-08 - accuracy: 0.3620 - val_loss: 5.8279e-08 - val_accuracy: 0.3621
Epoch 16/20
9/9 [==============================] - 1s 161ms/step - loss: 5.6495e-08 - accuracy: 0.3697 - val_loss: 5.8279e-08 - val_accuracy: 0.3665
Epoch 17/20
9/9 [==============================] - 1s 163ms/step - loss: 5.6495e-08 - accuracy: 0.3663 - val_loss: 5.8279e-08 - val_accuracy: 0.3674
Epoch 18/20
9/9 [==============================] - 2s 181ms/step - loss: 5.6495e-08 - accuracy: 0.3633 - val_loss: 5.8279e-08 - val_accuracy: 0.3701
Epoch 19/20
9/9 [==============================] - 1s 143ms/step - loss: 5.6495e-08 - accuracy: 0.3770 - val_loss: 5.8279e-08 - val_accuracy: 0.3719
Epoch 20/20
9/9 [==============================] - 1s 154ms/step - loss: 5.6495e-08 - accuracy: 0.3779 - val_loss: 5.8279e-08 - val_accuracy: 0.3741

---------------------------------------------------------------

############################ Model: categorical_crossentropy@adamax ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 1s 156ms/step - loss: 5.6495e-08 - accuracy: 0.4637 - val_loss: 5.8279e-08 - val_accuracy: 0.2402
Epoch 2/20
9/9 [==============================] - 1s 131ms/step - loss: 5.6495e-08 - accuracy: 0.4603 - val_loss: 5.8279e-08 - val_accuracy: 0.3078
Epoch 3/20
9/9 [==============================] - 1s 146ms/step - loss: 5.6495e-08 - accuracy: 0.4585 - val_loss: 5.8279e-08 - val_accuracy: 0.3541
Epoch 4/20
9/9 [==============================] - 1s 149ms/step - loss: 5.6495e-08 - accuracy: 0.4631 - val_loss: 5.8279e-08 - val_accuracy: 0.3897
Epoch 5/20
9/9 [==============================] - 1s 152ms/step - loss: 5.6495e-08 - accuracy: 0.4586 - val_loss: 5.8279e-08 - val_accuracy: 0.4061
Epoch 6/20
9/9 [==============================] - 1s 147ms/step - loss: 5.6495e-08 - accuracy: 0.4578 - val_loss: 5.8279e-08 - val_accuracy: 0.4244
Epoch 7/20
9/9 [==============================] - 1s 146ms/step - loss: 5.6495e-08 - accuracy: 0.4548 - val_loss: 5.8279e-08 - val_accuracy: 0.4302
Epoch 8/20
9/9 [==============================] - 1s 141ms/step - loss: 5.6495e-08 - accuracy: 0.4575 - val_loss: 5.8279e-08 - val_accuracy: 0.4377
Epoch 9/20
9/9 [==============================] - 1s 147ms/step - loss: 5.6495e-08 - accuracy: 0.4654 - val_loss: 5.8279e-08 - val_accuracy: 0.4435
Epoch 10/20
9/9 [==============================] - 2s 173ms/step - loss: 5.6495e-08 - accuracy: 0.4559 - val_loss: 5.8279e-08 - val_accuracy: 0.4520
Epoch 11/20
9/9 [==============================] - 1s 143ms/step - loss: 5.6495e-08 - accuracy: 0.4616 - val_loss: 5.8279e-08 - val_accuracy: 0.4577
Epoch 12/20
9/9 [==============================] - 1s 153ms/step - loss: 5.6495e-08 - accuracy: 0.4619 - val_loss: 5.8279e-08 - val_accuracy: 0.4631
Epoch 13/20
9/9 [==============================] - 1s 141ms/step - loss: 5.6495e-08 - accuracy: 0.4548 - val_loss: 5.8279e-08 - val_accuracy: 0.4653
Epoch 14/20
9/9 [==============================] - 1s 156ms/step - loss: 5.6495e-08 - accuracy: 0.4635 - val_loss: 5.8279e-08 - val_accuracy: 0.4675
Epoch 15/20
9/9 [==============================] - 1s 166ms/step - loss: 5.6495e-08 - accuracy: 0.4585 - val_loss: 5.8279e-08 - val_accuracy: 0.4698
Epoch 16/20
9/9 [==============================] - 1s 145ms/step - loss: 5.6495e-08 - accuracy: 0.4619 - val_loss: 5.8279e-08 - val_accuracy: 0.4711
Epoch 17/20
9/9 [==============================] - 1s 137ms/step - loss: 5.6495e-08 - accuracy: 0.4563 - val_loss: 5.8279e-08 - val_accuracy: 0.4760
Epoch 18/20
9/9 [==============================] - 1s 130ms/step - loss: 5.6495e-08 - accuracy: 0.4539 - val_loss: 5.8279e-08 - val_accuracy: 0.4755
Epoch 19/20
9/9 [==============================] - 1s 149ms/step - loss: 5.6495e-08 - accuracy: 0.4479 - val_loss: 5.8279e-08 - val_accuracy: 0.4760
Epoch 20/20
9/9 [==============================] - 1s 141ms/step - loss: 5.6495e-08 - accuracy: 0.4545 - val_loss: 5.8279e-08 - val_accuracy: 0.4778

---------------------------------------------------------------

############################ Model: kl_divergence@adam ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 167ms/step - loss: 0.0420 - accuracy: 0.4577 - val_loss: 0.0019 - val_accuracy: 0.4889
Epoch 2/20
9/9 [==============================] - 1s 148ms/step - loss: 3.8300e-05 - accuracy: 0.4739 - val_loss: 6.4990e-04 - val_accuracy: 0.4889
Epoch 3/20
9/9 [==============================] - 1s 147ms/step - loss: 3.4658e-06 - accuracy: 0.4739 - val_loss: 3.5674e-04 - val_accuracy: 0.4889
Epoch 4/20
9/9 [==============================] - 1s 148ms/step - loss: 6.2572e-07 - accuracy: 0.4739 - val_loss: 2.3690e-04 - val_accuracy: 0.4889
Epoch 5/20
9/9 [==============================] - 1s 129ms/step - loss: 1.6939e-07 - accuracy: 0.4739 - val_loss: 1.7659e-04 - val_accuracy: 0.4889
Epoch 6/20
9/9 [==============================] - 1s 147ms/step - loss: -2.0242e-07 - accuracy: 0.4739 - val_loss: 1.3762e-04 - val_accuracy: 0.4889
Epoch 7/20
9/9 [==============================] - 1s 147ms/step - loss: -1.3199e-07 - accuracy: 0.4739 - val_loss: 1.1049e-04 - val_accuracy: 0.4889
Epoch 8/20
9/9 [==============================] - 1s 142ms/step - loss: -1.8429e-07 - accuracy: 0.4739 - val_loss: 8.9769e-05 - val_accuracy: 0.4889
Epoch 9/20
9/9 [==============================] - 1s 135ms/step - loss: -1.5588e-07 - accuracy: 0.4739 - val_loss: 7.3504e-05 - val_accuracy: 0.4889
Epoch 10/20
9/9 [==============================] - 1s 160ms/step - loss: -7.7532e-08 - accuracy: 0.4739 - val_loss: 6.0444e-05 - val_accuracy: 0.4889
Epoch 11/20
9/9 [==============================] - 1s 155ms/step - loss: -2.1100e-07 - accuracy: 0.4739 - val_loss: 4.9974e-05 - val_accuracy: 0.4889
Epoch 12/20
9/9 [==============================] - 1s 151ms/step - loss: -1.6502e-07 - accuracy: 0.4739 - val_loss: 4.1432e-05 - val_accuracy: 0.4889
Epoch 13/20
9/9 [==============================] - 1s 150ms/step - loss: -2.2157e-07 - accuracy: 0.4739 - val_loss: 3.4513e-05 - val_accuracy: 0.4889
Epoch 14/20
9/9 [==============================] - 1s 153ms/step - loss: -2.2686e-07 - accuracy: 0.4739 - val_loss: 2.8878e-05 - val_accuracy: 0.4889
Epoch 15/20
9/9 [==============================] - 1s 142ms/step - loss: -1.9863e-07 - accuracy: 0.4739 - val_loss: 2.4201e-05 - val_accuracy: 0.4889
Epoch 16/20
9/9 [==============================] - 1s 152ms/step - loss: -2.9786e-07 - accuracy: 0.4739 - val_loss: 2.0366e-05 - val_accuracy: 0.4889
Epoch 17/20
9/9 [==============================] - 1s 138ms/step - loss: -2.3155e-07 - accuracy: 0.4739 - val_loss: 1.7229e-05 - val_accuracy: 0.4889
Epoch 18/20
9/9 [==============================] - 1s 144ms/step - loss: -2.4448e-07 - accuracy: 0.4739 - val_loss: 1.4620e-05 - val_accuracy: 0.4889
Epoch 19/20
9/9 [==============================] - 2s 169ms/step - loss: -2.5290e-07 - accuracy: 0.4739 - val_loss: 1.2455e-05 - val_accuracy: 0.4889
Epoch 20/20
9/9 [==============================] - 1s 152ms/step - loss: -1.8516e-07 - accuracy: 0.4739 - val_loss: 1.0651e-05 - val_accuracy: 0.4889

---------------------------------------------------------------

############################ Model: kl_divergence@sgd ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 198ms/step - loss: 0.2905 - accuracy: 0.5061 - val_loss: 0.2634 - val_accuracy: 0.4889
Epoch 2/20
9/9 [==============================] - 2s 196ms/step - loss: 0.2006 - accuracy: 0.4743 - val_loss: 0.2119 - val_accuracy: 0.4889
Epoch 3/20
9/9 [==============================] - 1s 165ms/step - loss: 0.1539 - accuracy: 0.4743 - val_loss: 0.1826 - val_accuracy: 0.4889
Epoch 4/20
9/9 [==============================] - 2s 198ms/step - loss: 0.1248 - accuracy: 0.4740 - val_loss: 0.1628 - val_accuracy: 0.4889
Epoch 5/20
9/9 [==============================] - 1s 142ms/step - loss: 0.1052 - accuracy: 0.4739 - val_loss: 0.1478 - val_accuracy: 0.4889
Epoch 6/20
9/9 [==============================] - 2s 178ms/step - loss: 0.0899 - accuracy: 0.4739 - val_loss: 0.1359 - val_accuracy: 0.4889
Epoch 7/20
9/9 [==============================] - 2s 172ms/step - loss: 0.0799 - accuracy: 0.4739 - val_loss: 0.1259 - val_accuracy: 0.4889
Epoch 8/20
9/9 [==============================] - 1s 166ms/step - loss: 0.0720 - accuracy: 0.4739 - val_loss: 0.1172 - val_accuracy: 0.4889
Epoch 9/20
9/9 [==============================] - 2s 185ms/step - loss: 0.0646 - accuracy: 0.4739 - val_loss: 0.1095 - val_accuracy: 0.4889
Epoch 10/20
9/9 [==============================] - 1s 162ms/step - loss: 0.0581 - accuracy: 0.4739 - val_loss: 0.1028 - val_accuracy: 0.4889
Epoch 11/20
9/9 [==============================] - 2s 179ms/step - loss: 0.0539 - accuracy: 0.4739 - val_loss: 0.0966 - val_accuracy: 0.4889
Epoch 12/20
9/9 [==============================] - 1s 162ms/step - loss: 0.0497 - accuracy: 0.4739 - val_loss: 0.0910 - val_accuracy: 0.4889
Epoch 13/20
9/9 [==============================] - 1s 142ms/step - loss: 0.0464 - accuracy: 0.4739 - val_loss: 0.0858 - val_accuracy: 0.4889
Epoch 14/20
9/9 [==============================] - 1s 144ms/step - loss: 0.0433 - accuracy: 0.4739 - val_loss: 0.0809 - val_accuracy: 0.4889
Epoch 15/20
9/9 [==============================] - 1s 136ms/step - loss: 0.0401 - accuracy: 0.4739 - val_loss: 0.0765 - val_accuracy: 0.4889
Epoch 16/20
9/9 [==============================] - 1s 155ms/step - loss: 0.0379 - accuracy: 0.4739 - val_loss: 0.0723 - val_accuracy: 0.4889
Epoch 17/20
9/9 [==============================] - 1s 138ms/step - loss: 0.0361 - accuracy: 0.4739 - val_loss: 0.0684 - val_accuracy: 0.4889
Epoch 18/20
9/9 [==============================] - 1s 134ms/step - loss: 0.0338 - accuracy: 0.4739 - val_loss: 0.0647 - val_accuracy: 0.4889
Epoch 19/20
9/9 [==============================] - 1s 138ms/step - loss: 0.0324 - accuracy: 0.4739 - val_loss: 0.0612 - val_accuracy: 0.4889
Epoch 20/20
9/9 [==============================] - 1s 152ms/step - loss: 0.0309 - accuracy: 0.4739 - val_loss: 0.0579 - val_accuracy: 0.4889

---------------------------------------------------------------

############################ Model: kl_divergence@rmsprop ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20

9/9 [==============================] - 2s 193ms/step - loss: 0.0414 - accuracy: 0.4695 - val_loss: 0.0055 - val_accuracy: 0.4889
Epoch 2/20
9/9 [==============================] - 2s 173ms/step - loss: 3.4346e-04 - accuracy: 0.4739 - val_loss: 0.0044 - val_accuracy: 0.4889
Epoch 3/20
9/9 [==============================] - 1s 150ms/step - loss: 1.2422e-04 - accuracy: 0.4739 - val_loss: 0.0031 - val_accuracy: 0.4889
Epoch 4/20
9/9 [==============================] - 1s 148ms/step - loss: 5.0780e-05 - accuracy: 0.4739 - val_loss: 0.0021 - val_accuracy: 0.4889
Epoch 5/20
9/9 [==============================] - 1s 150ms/step - loss: 2.4842e-05 - accuracy: 0.4739 - val_loss: 0.0014 - val_accuracy: 0.4889
Epoch 6/20
9/9 [==============================] - 2s 168ms/step - loss: 1.3032e-05 - accuracy: 0.4739 - val_loss: 8.9569e-04 - val_accuracy: 0.4889
Epoch 7/20
9/9 [==============================] - 1s 154ms/step - loss: 6.8048e-06 - accuracy: 0.4739 - val_loss: 5.7686e-04 - val_accuracy: 0.4889
Epoch 8/20
9/9 [==============================] - 1s 167ms/step - loss: 3.6338e-06 - accuracy: 0.4739 - val_loss: 3.6545e-04 - val_accuracy: 0.4889
Epoch 9/20
9/9 [==============================] - 1s 151ms/step - loss: 1.6679e-06 - accuracy: 0.4739 - val_loss: 2.3542e-04 - val_accuracy: 0.4889
Epoch 10/20
9/9 [==============================] - 1s 150ms/step - loss: 6.6189e-07 - accuracy: 0.4739 - val_loss: 1.5185e-04 - val_accuracy: 0.4889
Epoch 11/20
9/9 [==============================] - 1s 153ms/step - loss: 1.1970e-07 - accuracy: 0.4739 - val_loss: 9.6201e-05 - val_accuracy: 0.4889
Epoch 12/20
9/9 [==============================] - 1s 149ms/step - loss: -2.3721e-07 - accuracy: 0.4739 - val_loss: 6.0541e-05 - val_accuracy: 0.4889
Epoch 13/20
9/9 [==============================] - 1s 156ms/step - loss: -4.0729e-07 - accuracy: 0.4739 - val_loss: 3.6390e-05 - val_accuracy: 0.4889
Epoch 14/20
9/9 [==============================] - 1s 149ms/step - loss: -6.0813e-07 - accuracy: 0.4739 - val_loss: 2.2933e-05 - val_accuracy: 0.4889
Epoch 15/20
9/9 [==============================] - 1s 158ms/step - loss: -6.9095e-07 - accuracy: 0.4739 - val_loss: 1.4606e-05 - val_accuracy: 0.4889
Epoch 16/20
9/9 [==============================] - 2s 178ms/step - loss: -7.4579e-07 - accuracy: 0.4739 - val_loss: 9.2681e-06 - val_accuracy: 0.4889
Epoch 17/20
9/9 [==============================] - 2s 191ms/step - loss: -7.7397e-07 - accuracy: 0.4739 - val_loss: 5.6930e-06 - val_accuracy: 0.4889
Epoch 18/20
9/9 [==============================] - 1s 147ms/step - loss: -7.9867e-07 - accuracy: 0.4739 - val_loss: 3.4443e-06 - val_accuracy: 0.4889
Epoch 19/20
9/9 [==============================] - 1s 149ms/step - loss: -8.0845e-07 - accuracy: 0.4739 - val_loss: 1.9095e-06 - val_accuracy: 0.4889
Epoch 20/20
9/9 [==============================] - 1s 160ms/step - loss: -8.2205e-07 - accuracy: 0.4739 - val_loss: 1.0116e-06 - val_accuracy: 0.4889

---------------------------------------------------------------

############################ Model: kl_divergence@adagrad ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 169ms/step - loss: 0.3157 - accuracy: 0.4393 - val_loss: 0.3045 - val_accuracy: 0.5294
Epoch 2/20
9/9 [==============================] - 1s 141ms/step - loss: 0.2712 - accuracy: 0.4688 - val_loss: 0.2731 - val_accuracy: 0.4889
Epoch 3/20
9/9 [==============================] - 1s 140ms/step - loss: 0.2379 - accuracy: 0.4710 - val_loss: 0.2516 - val_accuracy: 0.4889
Epoch 4/20
9/9 [==============================] - 1s 148ms/step - loss: 0.2107 - accuracy: 0.4789 - val_loss: 0.2356 - val_accuracy: 0.4889
Epoch 5/20
9/9 [==============================] - 1s 145ms/step - loss: 0.1915 - accuracy: 0.4770 - val_loss: 0.2224 - val_accuracy: 0.4889
Epoch 6/20
9/9 [==============================] - 1s 144ms/step - loss: 0.1753 - accuracy: 0.4750 - val_loss: 0.2113 - val_accuracy: 0.4889
Epoch 7/20
9/9 [==============================] - 1s 147ms/step - loss: 0.1611 - accuracy: 0.4739 - val_loss: 0.2017 - val_accuracy: 0.4889
Epoch 8/20
9/9 [==============================] - 1s 143ms/step - loss: 0.1497 - accuracy: 0.4743 - val_loss: 0.1931 - val_accuracy: 0.4889
Epoch 9/20
9/9 [==============================] - 1s 150ms/step - loss: 0.1395 - accuracy: 0.4739 - val_loss: 0.1854 - val_accuracy: 0.4889
Epoch 10/20
9/9 [==============================] - 1s 145ms/step - loss: 0.1312 - accuracy: 0.4738 - val_loss: 0.1783 - val_accuracy: 0.4889
Epoch 11/20
9/9 [==============================] - 1s 153ms/step - loss: 0.1235 - accuracy: 0.4740 - val_loss: 0.1717 - val_accuracy: 0.4889
Epoch 12/20
9/9 [==============================] - 1s 145ms/step - loss: 0.1171 - accuracy: 0.4740 - val_loss: 0.1655 - val_accuracy: 0.4889
Epoch 13/20
9/9 [==============================] - 1s 143ms/step - loss: 0.1110 - accuracy: 0.4739 - val_loss: 0.1596 - val_accuracy: 0.4889
Epoch 14/20
9/9 [==============================] - 2s 181ms/step - loss: 0.1066 - accuracy: 0.4739 - val_loss: 0.1540 - val_accuracy: 0.4889
Epoch 15/20
9/9 [==============================] - 1s 156ms/step - loss: 0.1012 - accuracy: 0.4739 - val_loss: 0.1486 - val_accuracy: 0.4889
Epoch 16/20
9/9 [==============================] - 1s 143ms/step - loss: 0.0956 - accuracy: 0.4739 - val_loss: 0.1435 - val_accuracy: 0.4889
Epoch 17/20
9/9 [==============================] - 1s 159ms/step - loss: 0.0929 - accuracy: 0.4739 - val_loss: 0.1387 - val_accuracy: 0.4889
Epoch 18/20
9/9 [==============================] - 1s 150ms/step - loss: 0.0892 - accuracy: 0.4739 - val_loss: 0.1339 - val_accuracy: 0.4889
Epoch 19/20
9/9 [==============================] - 1s 143ms/step - loss: 0.0851 - accuracy: 0.4739 - val_loss: 0.1294 - val_accuracy: 0.4889
Epoch 20/20
9/9 [==============================] - 1s 137ms/step - loss: 0.0830 - accuracy: 0.4739 - val_loss: 0.1250 - val_accuracy: 0.4889

---------------------------------------------------------------

############################ Model: kl_divergence@adadelta ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20

9/9 [==============================] - 2s 226ms/step - loss: 0.3477 - accuracy: 0.4037 - val_loss: 0.3485 - val_accuracy: 0.2647
Epoch 2/20
9/9 [==============================] - 1s 132ms/step - loss: 0.3448 - accuracy: 0.3915 - val_loss: 0.3445 - val_accuracy: 0.3092
Epoch 3/20
9/9 [==============================] - 1s 135ms/step - loss: 0.3387 - accuracy: 0.3971 - val_loss: 0.3409 - val_accuracy: 0.3092
Epoch 4/20
9/9 [==============================] - 2s 219ms/step - loss: 0.3331 - accuracy: 0.3998 - val_loss: 0.3373 - val_accuracy: 0.3012
Epoch 5/20
9/9 [==============================] - 2s 180ms/step - loss: 0.3294 - accuracy: 0.4013 - val_loss: 0.3338 - val_accuracy: 0.3238
Epoch 6/20
9/9 [==============================] - 2s 184ms/step - loss: 0.3210 - accuracy: 0.4160 - val_loss: 0.3304 - val_accuracy: 0.3403
Epoch 7/20
9/9 [==============================] - 2s 182ms/step - loss: 0.3163 - accuracy: 0.4183 - val_loss: 0.3270 - val_accuracy: 0.3550
Epoch 8/20
9/9 [==============================] - 2s 211ms/step - loss: 0.3111 - accuracy: 0.4147 - val_loss: 0.3236 - val_accuracy: 0.3665
Epoch 9/20
9/9 [==============================] - 2s 210ms/step - loss: 0.3067 - accuracy: 0.4090 - val_loss: 0.3202 - val_accuracy: 0.3866
Epoch 10/20
9/9 [==============================] - 2s 187ms/step - loss: 0.3019 - accuracy: 0.4222 - val_loss: 0.3169 - val_accuracy: 0.4030
Epoch 11/20
9/9 [==============================] - 1s 162ms/step - loss: 0.2959 - accuracy: 0.4287 - val_loss: 0.3136 - val_accuracy: 0.4173
Epoch 12/20
9/9 [==============================] - 2s 170ms/step - loss: 0.2932 - accuracy: 0.4287 - val_loss: 0.3103 - val_accuracy: 0.4328
Epoch 13/20
9/9 [==============================] - 2s 205ms/step - loss: 0.2871 - accuracy: 0.4331 - val_loss: 0.3070 - val_accuracy: 0.4422
Epoch 14/20
9/9 [==============================] - 2s 206ms/step - loss: 0.2815 - accuracy: 0.4451 - val_loss: 0.3038 - val_accuracy: 0.4484
Epoch 15/20
9/9 [==============================] - 2s 181ms/step - loss: 0.2790 - accuracy: 0.4464 - val_loss: 0.3005 - val_accuracy: 0.4600
Epoch 16/20
9/9 [==============================] - 2s 169ms/step - loss: 0.2737 - accuracy: 0.4477 - val_loss: 0.2973 - val_accuracy: 0.4680
Epoch 17/20
9/9 [==============================] - 2s 189ms/step - loss: 0.2701 - accuracy: 0.4518 - val_loss: 0.2940 - val_accuracy: 0.4715
Epoch 18/20
9/9 [==============================] - 2s 194ms/step - loss: 0.2665 - accuracy: 0.4506 - val_loss: 0.2908 - val_accuracy: 0.4733
Epoch 19/20
9/9 [==============================] - 2s 180ms/step - loss: 0.2613 - accuracy: 0.4549 - val_loss: 0.2875 - val_accuracy: 0.4738
Epoch 20/20
9/9 [==============================] - 2s 268ms/step - loss: 0.2570 - accuracy: 0.4590 - val_loss: 0.2843 - val_accuracy: 0.4751

---------------------------------------------------------------

############################ Model: kl_divergence@adamax ############################

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
batch_normalization (BatchNo (None, 121)               484
_________________________________________________________________
dense (Dense)                (None, 1024)              124928
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              1049600
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 1025
=================================================================
Total params: 1,176,037
Trainable params: 1,175,795
Non-trainable params: 242
_________________________________________________________________

Epoch 1/20
9/9 [==============================] - 2s 195ms/step - loss: 0.0442 - accuracy: 0.4650 - val_loss: 0.0066 - val_accuracy: 0.4889
Epoch 2/20
9/9 [==============================] - 1s 156ms/step - loss: 6.4757e-04 - accuracy: 0.4739 - val_loss: 0.0044 - val_accuracy: 0.4889
Epoch 3/20
9/9 [==============================] - 2s 179ms/step - loss: 2.7913e-04 - accuracy: 0.4739 - val_loss: 0.0037 - val_accuracy: 0.4889
Epoch 4/20
9/9 [==============================] - 1s 157ms/step - loss: 1.6856e-04 - accuracy: 0.4739 - val_loss: 0.0032 - val_accuracy: 0.4889
Epoch 5/20
9/9 [==============================] - 2s 173ms/step - loss: 1.3635e-04 - accuracy: 0.4739 - val_loss: 0.0028 - val_accuracy: 0.4889
Epoch 6/20
9/9 [==============================] - 2s 169ms/step - loss: 1.0677e-04 - accuracy: 0.4739 - val_loss: 0.0025 - val_accuracy: 0.4889
Epoch 7/20
9/9 [==============================] - 2s 170ms/step - loss: 9.7951e-05 - accuracy: 0.4739 - val_loss: 0.0022 - val_accuracy: 0.4889
Epoch 8/20
9/9 [==============================] - 1s 165ms/step - loss: 9.3092e-05 - accuracy: 0.4739 - val_loss: 0.0019 - val_accuracy: 0.4889
Epoch 9/20
9/9 [==============================] - 2s 169ms/step - loss: 8.0980e-05 - accuracy: 0.4739 - val_loss: 0.0016 - val_accuracy: 0.4889
Epoch 10/20
9/9 [==============================] - 2s 203ms/step - loss: 7.2205e-05 - accuracy: 0.4739 - val_loss: 0.0014 - val_accuracy: 0.4889
Epoch 11/20
9/9 [==============================] - 2s 171ms/step - loss: 6.3360e-05 - accuracy: 0.4739 - val_loss: 0.0012 - val_accuracy: 0.4889
Epoch 12/20
9/9 [==============================] - 1s 159ms/step - loss: 5.7901e-05 - accuracy: 0.4739 - val_loss: 9.7975e-04 - val_accuracy: 0.4889
Epoch 13/20
9/9 [==============================] - 1s 155ms/step - loss: 4.9496e-05 - accuracy: 0.4739 - val_loss: 8.2166e-04 - val_accuracy: 0.4889
Epoch 14/20
9/9 [==============================] - 2s 167ms/step - loss: 4.5972e-05 - accuracy: 0.4739 - val_loss: 6.8758e-04 - val_accuracy: 0.4889
Epoch 15/20
9/9 [==============================] - 2s 173ms/step - loss: 3.9594e-05 - accuracy: 0.4739 - val_loss: 5.7369e-04 - val_accuracy: 0.4889
Epoch 16/20
9/9 [==============================] - 2s 168ms/step - loss: 3.6448e-05 - accuracy: 0.4739 - val_loss: 4.7820e-04 - val_accuracy: 0.4889
Epoch 17/20
9/9 [==============================] - 2s 174ms/step - loss: 3.1349e-05 - accuracy: 0.4739 - val_loss: 3.9971e-04 - val_accuracy: 0.4889
Epoch 18/20
9/9 [==============================] - 2s 173ms/step - loss: 3.1910e-05 - accuracy: 0.4739 - val_loss: 3.3383e-04 - val_accuracy: 0.4889
Epoch 19/20
9/9 [==============================] - 1s 149ms/step - loss: 2.6682e-05 - accuracy: 0.4739 - val_loss: 2.7715e-04 - val_accuracy: 0.4889
Epoch 20/20
9/9 [==============================] - 2s 181ms/step - loss: 2.3608e-05 - accuracy: 0.4739 - val_loss: 2.3185e-04 - val_accuracy: 0.4889

### Model Metrics for various Models

In [73]:
md = {}
for model in models:
    pred = models[model].predict(x_test)
    for i in range(len(pred)):
        pred[i] = 1 if pred[i] > 0.5 else 0
    print("\n---------------------------------------------------------------------\nAccuracy Score of "+model,"As per TF",accuracy_score(y_test,pred))
    print("####### Using Confusin Matrix #######\n")
    accuracy, precision, recall = generateConfusionMatrix(y_test, pred)
    if md.get(model.split('@')[0]) is None:
        md[model.split('@')[0]] = { model : accuracy }
    else:
        md[model.split('@')[0]][ model ] = accuracy
    print(model+"*"+"\n\tAccuracy : {0} \n\tPrecision : {1} \n\tRecall : {2}".format(accuracy, precision, recall))

---------------------------------------------------------------------
Accuracy Score of binary_crossentropy@adam As per TF 0.9893238434163701
####### Using Confusin Matrix #######

True Positive:	1078
    True Negative:
1146
    False Positive:
3
    False Negative:
21

binary_crossentropy@adam*
	Accuracy : 0.9893238434163701
	Precision : 0.9972247918593895
	Recall : 0.9808917197452229

---------------------------------------------------------------------
Accuracy Score of binary_crossentropy@sgd As per TF 0.9653024911032029
####### Using Confusin Matrix #######

True Positive:	1028
    True Negative:
1142
    False Positive:
7
    False Negative:
71

binary_crossentropy@sgd*
	Accuracy : 0.9653024911032029
	Precision : 0.9932367149758454
	Recall : 0.935395814376706

---------------------------------------------------------------------
Accuracy Score of binary_crossentropy@rmsprop As per TF 0.9902135231316725
####### Using Confusin Matrix #######

True Positive:	1082
    True Negative:
1144
    False Positive:
5
    False Negative:
17

binary_crossentropy@rmsprop*
	Accuracy : 0.9902135231316725
	Precision : 0.9954001839926403
	Recall : 0.9845313921747043

---------------------------------------------------------------------
Accuracy Score of binary_crossentropy@adagrad As per TF 0.9684163701067615
####### Using Confusin Matrix #######

True Positive:	1048
    True Negative:
1129
    False Positive:
20
    False Negative:
51

binary_crossentropy@adagrad*
	Accuracy : 0.9684163701067615
	Precision : 0.9812734082397003
	Recall : 0.9535941765241128

---------------------------------------------------------------------
Accuracy Score of binary_crossentropy@adadelta As per TF 0.9092526690391459
####### Using Confusin Matrix #######

True Positive:	928
    True Negative:
1116
    False Positive:
33
    False Negative:
171

binary_crossentropy@adadelta*
	Accuracy : 0.9092526690391459
	Precision : 0.9656607700312175
	Recall : 0.8444040036396724

---------------------------------------------------------------------
Accuracy Score of binary_crossentropy@adamax As per TF 0.9879893238434164
####### Using Confusin Matrix #######

True Positive:	1081
    True Negative:
1140
    False Positive:
9
    False Negative:
18

binary_crossentropy@adamax*
	Accuracy : 0.9879893238434164
	Precision : 0.9917431192660551
	Recall : 0.9836214740673339

---------------------------------------------------------------------
Accuracy Score of categorical_crossentropy@adam As per TF 0.5204626334519573
####### Using Confusin Matrix #######

True Positive:	602
    True Negative:
568
    False Positive:
581
    False Negative:
497

categorical_crossentropy@adam*
	Accuracy : 0.5204626334519573
	Precision : 0.5088757396449705
	Recall : 0.5477707006369427

---------------------------------------------------------------------
Accuracy Score of categorical_crossentropy@sgd As per TF 0.3634341637010676
####### Using Confusin Matrix #######

True Positive:	799
    True Negative:
18
    False Positive:
1131
    False Negative:
300

categorical_crossentropy@sgd*
	Accuracy : 0.3634341637010676
	Precision : 0.4139896373056995
	Recall : 0.727024567788899

---------------------------------------------------------------------
Accuracy Score of categorical_crossentropy@rmsprop As per TF 0.5435943060498221
####### Using Confusin Matrix #######

True Positive:	76
    True Negative:
1146
    False Positive:
3
    False Negative:
1023

categorical_crossentropy@rmsprop*
	Accuracy : 0.5435943060498221
	Precision : 0.9620253164556962
	Recall : 0.06915377616014559

---------------------------------------------------------------------
Accuracy Score of categorical_crossentropy@adagrad As per TF 0.4986654804270463
####### Using Confusin Matrix #######

True Positive:	894
    True Negative:
227
    False Positive:
922
    False Negative:
205

categorical_crossentropy@adagrad*
	Accuracy : 0.4986654804270463
	Precision : 0.4922907488986784
	Recall : 0.813466787989081

---------------------------------------------------------------------
Accuracy Score of categorical_crossentropy@adadelta As per TF 0.3741103202846975
####### Using Confusin Matrix #######

True Positive:	649
    True Negative:
192
    False Positive:
957
    False Negative:
450

categorical_crossentropy@adadelta*
	Accuracy : 0.3741103202846975
	Precision : 0.4041095890410959
	Recall : 0.5905368516833485

---------------------------------------------------------------------
Accuracy Score of categorical_crossentropy@adamax As per TF 0.4777580071174377
####### Using Confusin Matrix #######

True Positive:	386
    True Negative:
688
    False Positive:
461
    False Negative:
713

categorical_crossentropy@adamax*
	Accuracy : 0.4777580071174377
	Precision : 0.4557260920897285
	Recall : 0.35122838944494994

---------------------------------------------------------------------
Accuracy Score of kl_divergence@adam As per TF 0.4888790035587189
####### Using Confusin Matrix #######

True Positive:	1099
    True Negative:
0
    False Positive:
1149
    False Negative:
0

kl_divergence@adam*
	Accuracy : 0.4888790035587189
	Precision : 0.4888790035587189
	Recall : 1.0

---------------------------------------------------------------------
Accuracy Score of kl_divergence@sgd As per TF 0.4888790035587189
####### Using Confusin Matrix #######

True Positive:	1099
    True Negative:
0
    False Positive:
1149
    False Negative:
0

kl_divergence@sgd*
	Accuracy : 0.4888790035587189
	Precision : 0.4888790035587189
	Recall : 1.0

---------------------------------------------------------------------
Accuracy Score of kl_divergence@rmsprop As per TF 0.4888790035587189
####### Using Confusin Matrix #######

True Positive:	1099
    True Negative:
0
    False Positive:
1149
    False Negative:
0

kl_divergence@rmsprop*
	Accuracy : 0.4888790035587189
	Precision : 0.4888790035587189
	Recall : 1.0

---------------------------------------------------------------------
Accuracy Score of kl_divergence@adagrad As per TF 0.4888790035587189
####### Using Confusin Matrix #######

True Positive:	1099
    True Negative:
0
    False Positive:
1149
    False Negative:
0

kl_divergence@adagrad*
	Accuracy : 0.4888790035587189
	Precision : 0.4888790035587189
	Recall : 1.0

---------------------------------------------------------------------
Accuracy Score of kl_divergence@adadelta As per TF 0.4750889679715303
####### Using Confusin Matrix #######

True Positive:	1068
    True Negative:
0
    False Positive:
1149
    False Negative:
31

kl_divergence@adadelta*
	Accuracy : 0.4750889679715303
	Precision : 0.4817320703653586
	Recall : 0.9717925386715196

---------------------------------------------------------------------
Accuracy Score of kl_divergence@adamax As per TF 0.4888790035587189
####### Using Confusin Matrix #######

True Positive:	1099
    True Negative:
0
    False Positive:
1149
    False Negative:
0

kl_divergence@adamax*
	Accuracy : 0.4888790035587189
	Precision : 0.4888790035587189
	Recall : 1.0

### Top 3 Models of individual Loss Functions across 6 optimizers

In [74]:
for i in md:
  md[i] = { k: v for k, v in sorted(md[i].items(),reverse=True, key=lambda item: item[1]) }
  #print(md[i])
  print("\n------------------------------------------\nTop 3 Models and optimizers of",i)
  c = 0
  for a in md[i]:
    if c > 2 : break
    print("# Using "+a.split("@")[1]+" as optimizer\t\tAccuracy: "+str(md[i][a])+"\t(Model Name: "+a+")")
    c += 1

------------------------------------------
Top 3 Models and optimizers of binary_crossentropy
# Using rmsprop as optimizer		Accuracy: 0.9902135231316725	(Model Name: binary_crossentropy@rmsprop)
# Using adam as optimizer		Accuracy: 0.9893238434163701	(Model Name: binary_crossentropy@adam)
# Using adamax as optimizer		Accuracy: 0.9879893238434164	(Model Name: binary_crossentropy@adamax)

------------------------------------------
Top 3 Models and optimizers of categorical_crossentropy
# Using rmsprop as optimizer		Accuracy: 0.5435943060498221	(Model Name: categorical_crossentropy@rmsprop)
# Using adam as optimizer		Accuracy: 0.5204626334519573	(Model Name: categorical_crossentropy@adam)
# Using adagrad as optimizer		Accuracy: 0.4986654804270463	(Model Name: categorical_crossentropy@adagrad)

------------------------------------------
Top 3 Models and optimizers of kl_divergence
# Using adam as optimizer		Accuracy: 0.4888790035587189	(Model Name: kl_divergence@adam)
# Using sgd as optimizer		Accuracy: 0.4888790035587189	(Model Name: kl_divergence@sgd)
# Using rmsprop as optimizer		Accuracy: 0.4888790035587189	(Model Name: kl_divergence@rmsprop)

### Saving Model And Vectorizer

In [97]:
from tensorflow.keras.models import load_model
import cloudpickle

best_model = 'binary_crossentropy@adam'
print("###Saving Model###")
try:
    models[best_model].save(best_model+'-Final-SQLI-Model.h5')
    print("\t\tSaved Model Successfully!")
except:
    print("\t\t Failed to save Model!")
print('\n###Saving Vectorizer###')
try:
    #with open('Final-SQLI-Vectorizer', 'wb') as fin:
    with open('New-Final-SQLI-Vectorizer', 'wb') as vecortizer:
        #pickle.dump(vectorizer, fin)
        cloudpickle.dump(nv, vecortizer)
    print("\t\tSaved Vectorizer Successfully!")
except:
    print("\t\t Failed to save Vectorizer!")

###Saving Model###
		Saved Model Successfully!

###Saving Vectorizer###
		Saved Vectorizer Successfully!

### Load Model, Vectorizer and Manual Testing

     This cell is also in file user_Data_predict.py

In [ ]:
%pip install --upgrade cloudpickle
%pip freeze

### Testing

In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow.keras as keras
from tensorflow.keras.models import load_model
import cloudpickle
import pandas as pd
import re

models = { "binary_crossentropy@adam" : load_model('binary_crossentropy@adam-Final-SQLI-Model.h5') }
md = {}
for model in models:
    pred = models[model].predict(x_test)
    for i in range(len(pred)):
        pred[i] = 1 if pred[i] > 0.5 else 0
    print("\n---------------------------------------------------------------------\nAccuracy Score of "+model,"As per TF",accuracy_score(y_test,pred))
    print("####### Using Confusin Matrix #######\n")
    accuracy, precision, recall = generateConfusionMatrix(y_test, pred)
    if md.get(model.split('@')[0]) is None:
        md[model.split('@')[0]] = { model : accuracy }
    else:
        md[model.split('@')[0]][ model ] = accuracy
    print(model+"*"+"\n\tAccuracy : {0} \n\tPrecision : {1} \n\tRecall : {2}".format(accuracy, precision, recall))

class Intelligent:
    mymodel = load_model('binary_crossentropy@adam-Final-SQLI-Model.h5')
    myvectorizer = cloudpickle.load(open('New-Final-SQLI-Vectorizer', 'rb'))
    myvectorizer = staticmethod(myvectorizer)
    def predict_sqli_attack(self,input_val=0,verbose=False):
        def clean_data(inp):
            inp = inp.replace('\n', '')
            inp = inp.replace('%20', ' ')
            inp = inp.replace('/', ' ')
            inp = inp.replace('_', ' _ ')
            inp = inp.replace('?', ' ? ')
            inp = inp.replace('.', ' . ')
            inp = inp.replace('=', ' ')
            inp = re.sub(r"\d+", "numeric", inp) 

            return inp

        def out(s):
            if verbose:
                print(s)
        repeat = True
        beautify = ''
        for i in range(20):
            beautify += "="
        zip=False
        if input_val == 0:
            zip = True
            out(beautify+"\nEnter 0 anytime to exit!\n"+beautify) 
            input_val = input("Give me some data to work on : \n")
            out(beautify)

        if input_val == '0':
            repeat = False    
        
        input_val = clean_data(input_val)
        clr_str = input_val

        # Vectorization with New Vectorizer
        print("Cleaned Input:",input_val)
        input_val = self.myvectorizer(inp=input_val)

        result = self.mymodel.predict(input_val)
        out(beautify) 

        if repeat == True and zip == True :
            if result > 0.5:
                print(result,"ALERT :::: This can be SQL injection")
            elif result <= 0.5:
                print(result,"It seems to be safe") 
            out(beautify)
            self.predict_sqli_attack()
        else:
            #if result>0.5:print(clr_str)
            return(result)

zop = Intelligent()

In [ ]:
zop.predict_sqli_attack()

# Other Possible Vectorization criteria Ideas

In [ ]:
def distance_between_words(string, word1, word2):
     
    if word1 == word2 :
       return 0
    words = string.lower().split(" ")
    min_dist = len(words)+1
    for index in range(len(words)):
        if words[index] == word1:
            for search in range(len(words)):
                if words[search] == word2:
                    curr = abs(index - search) - 1
                    if curr < min_dist:
                       min_dist = curr

    return min_dist

In [ ]:
path = './data/sqli_for_training.txt'
test_word1='select'
test_word2='from'
test_data = []
file = open(path, "r")
t = {}
for x in file:
    w=distance_between_words(x , test_word1, test_word2)
    if t.get(str(w)) is None:
        t[str(w)]=0
    else:
        t[str(w)]+=1
    test_data.append(w)

from matplotlib import pyplot as plt
k=list(t.keys())
k = sorted(k, key=lambda x: int(x), reverse=False)
ww = {i: t[i] for i in k}
plt.bar(range(len(ww)), list(ww.values()), align='center')
plt.xticks(range(len(ww)), list(ww.keys()))
plt.title("Distance between `"+test_word1+"` and `"+test_word2+"`")
plt.show()

In [ ]:
path = './data/sqli_for_training.txt'
test_word1='from'
test_word2='where'
test_data = []
file = open(path, "r")
t = {}
for x in file:
    w=distance_between_words(x , test_word1, test_word2)
    if t.get(str(w)) is None:
        t[str(w)]=0
    else:
        t[str(w)]+=1
    test_data.append(w)

from matplotlib import pyplot as plt
k=list(t.keys())
k = sorted(k, key=lambda x: int(x), reverse=False)
ww = {i: t[i] for i in k}
plt.bar(range(len(ww)), list(ww.values()), align='center')
plt.xticks(range(len(ww)), list(ww.keys()))
plt.title("Distance between `"+test_word1+"` and `"+test_word2+"`")
plt.show()